In [2]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
from matplotlib import patches as mpatches
plt.style.use('seaborn')
import seaborn as sns
import time
import sys
import os
import scipy.stats as st
from utils.embedding_utils import multiple_embedding_analysis
from utils.roi_utils import meg_roi_network_assigments
# ignore warnings
import warnings
warnings.filterwarnings('ignore');

# display multiple outputs within a cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all";

In [3]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

In [4]:
DATA_ROOT=r'C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\data\MEG'
clinical_file=os.path.join(DATA_ROOT,'MEG.clinical.csv')
clinical_df = pd.read_csv(clinical_file)

In [5]:
template_file = os.path.join(DATA_ROOT,'AALtemplate_balanced.csv')
template_df = pd.read_csv(template_file)
# template_df= template_df.apply(lambda row: meg_roi_network_assigments(row,combine_dmn=False),axis=1)

In [6]:
label_options = {'FN':'Functional Net','SOB':'SOB','FN_SOB':'Func Net SOB','All':'All'}
label=label_options['FN']

In [7]:
study_dirs=[ r"C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\ds\pats_CogTr1\L3\HGCN_full_findc_id_dp",]

In [8]:
# for s in study_dirs[:1]:
# # this *could* be done with the same logic as study_ds and the others
# # but really, is it necissary?
# # we could also just do a full walk of the data from the root?
#     save_dir=s
#     all_roots=[os.path.join(s,r) for r in os.listdir(s) if '.csv' not in r  and ('.json' not in r) ]
#     try:
#         all_stat_dicts,full_dict,all_stat_dfs,full_stat_df = multiple_embedding_analysis(all_roots,clinical_df,label,net_threshold=.29,
#                                        template_df=template_df,save_dir=save_dir,suffix='.csv',balanced_atl=True,average=True)
#     except:

In [9]:
def ingest_all_embeddings_in_subtree(root):
    for (subroot,dirs,files) in os.walk(root, topdown=True):
        print('NEXT LEVEL??')
    #     print(root,dirs,files)
        if not dirs :
            continue
        embedding_roots=[]
    #     full_dirs=p
    #         os.path.join(s,r) for r in os.listdir(s) if '.csv' not in r  and ('.json' not in r) ]
        for d in dirs:
            full_dir=os.path.join(subroot,d)
            subfiles=os.listdir(full_dir)
            if ('finish_train.txt' in subfiles) or ('model.pth' in subfiles) or ('final_model.pth' in subfiles):
                embedding_roots.append(full_dir)
        if embedding_roots:
            print(subroot,embedding_roots)
            
        all_stat_dicts,full_dict,all_stat_dfs,full_stat_df = multiple_embedding_analysis(embedding_roots,clinical_df,label,net_threshold=.29,
                                       template_df=template_df,save_dir=subroot,suffix='.csv',balanced_atl=True,average=True)

In [24]:
# root= r'C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\ds\all_pats'
# root= r'C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\ds\all_pats\L3'
# root=r'C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\ds\all_pats\L3\HGCN_full_0.54c_plv_dp\e60_p6_lr0.021_vpct0_tpct0_stretch98_b8'
root=r'C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p6_lr0.021_vpct0.3_tpct0.2_stretch98_b8'

root=r'C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\ds\pats_CogTr1\L3\HGCN_full_findc_plv_dp\e5_p6_lr0.021_vpct0_tpct0_stretch98_b8'
root=r'C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_findc_plv_dp\e50_p6_lr0.021_vpct0.2_tpct0.1_stretch98_b8'
root=r'C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27'
ingest_all_embeddings_in_subtree(root)


NEXT LEVEL??
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27 ['C:\\Users\\coleb\\OneDrive\\Desktop\\Fall 2021\\Neuro\\hgcn\\logs\\meg\\lp\\2023_2_27\\1', 'C:\\Users\\coleb\\OneDrive\\Desktop\\Fall 2021\\Neuro\\hgcn\\logs\\meg\\lp\\2023_2_27\\2']
tensor([0.5400], dtype=torch.float64) layer of c 0
0.54 listed c
tensor([0.5400], dtype=torch.float64) layer of c 1
0.54 listed c
2.0 1.0 0.54
r t c
alpha BANDS
0 ID please?
1 PLV
0 graph norm?
{'train': [0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 30, 31, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 128, 129, 130, 131, 132, 133, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\8_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\9_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Func

[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\21_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5:

FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\33_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\34_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 

[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\46_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5:

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\58_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\59_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Fu

[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\71_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5:

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\83_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\84_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Fu

[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\96_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5:

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\108_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\109_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS


[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\121_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5

FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\133_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\134_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN'

[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\146_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\158_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\159_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS


[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\1\embeddings\171_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5

pDMN Bin    10
aDMN Bin     6
DAN Bin      6
FPN Bin     12
VN Bin      12
VAN Bin     14
SN Bin      12
SMN Bin      4
dtype: int64 eyyy
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\0_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\1_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2

[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\13_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5:

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\25_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\26_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Fu

[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\38_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5:

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\50_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\51_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Fu

[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\63_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5:

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\75_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\76_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Fu

[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\88_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5:

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\100_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\101_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS


[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\113_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5

FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\125_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\126_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN'

[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\138_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5

FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\150_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\151_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN'

[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\163_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\175_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hgcn\logs\meg\lp\2023_2_27\2\embeddings\176_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS


(180, 153) og shape
(180, 153) DF SHAPE
(180, 153) DF SHAPE
(180, 90) conccat
(180, 90) SHAPE
     Pre  Scan Index        ID  CogTr  diagnosis  pre_MMSE  pre_7MS  pre_BNT  \
0      1           0  UMEC-002      1          1      30.0     89.0     60.0   
1      0           1  UMEC-002      1          1      30.0     89.0     60.0   
2      1           2  UMEC-020      1          1      30.0     79.0      NaN   
3      0           3  UMEC-020      1          1      30.0     79.0      NaN   
4      1           4  UMEC-022      1          1      29.0     62.0     49.0   
..   ...         ...       ...    ...        ...       ...      ...      ...   
175    0         175  UMEC-213      2          2      29.0     73.0     57.0   
176    1         176  UMEC-214      2          2      30.0     89.0     54.0   
177    0         177  UMEC-214      2          2      30.0     89.0     54.0   
178    1         178  UMEC-216      2          2      30.0     74.0     56.0   
179    0         179  UMEC

In [18]:
lp_root= r'C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats'
lp_dir=os.path.join(lp_root,'L3')
ingest_all_embeddings_in_subtree(lp_dir)


NEXT LEVEL??
No successful embeddings
NEXT LEVEL??
No successful embeddings
NEXT LEVEL??
NEXT LEVEL??
No successful embeddings
NEXT LEVEL??
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8 ['C:\\Users\\coleb\\OneDrive\\Desktop\\Fall 2021\\Neuro\\hyperBrain\\study\\meg\\lp\\all_pats\\L3\\HGCN_full_0.54c_plv_dp\\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\\0']
embeddings not yet saved for C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0
Saving now.
Namespace(act='selu', adj_threshold=0.329, all_file='C:\\Users\\coleb\\OneDrive\\Desktop\\Fall 2021\\Neuro\\hyperBrain\\data/MEG\\meg_all_MEG_0.329.json', alpha=0.2, band='alpha', batch_size=8, bias=1, c=0.54, criteria_dict={}, cuda=0, currently_training=False, data_root='C:\\Users\\coleb\\OneDrive\\Desktop\\Fall 2021\\Neuro\\hyperBrai

False EXCLUSION
90 HOW MANY DID WE KEEP SHOULD BE 45
0.3 val pct
0.2 test_pct
54.0 NUM VAL
90
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
now test
(2, 64) matching rows
(2, 64) matching rows
whoopsie
(2, 64) matching rows
whoopsie
whoopsie
(2, 64) matching rows
whoopsie
(2, 64) matching rows
whoopsie
whoopsie
(2, 64) matching rows
whoopsie
(2, 64) matching rows
(2, 64) matching rows
(2, 64) matching rows
(2, 64) matching rows
(2, 64) matching rows
whoopsie
whoopsie
(2, 64) matching rows
(2, 64) matching rows
(2, 64) matching rows
(2, 64) matching rows
whoopsie
(2, 64) matching rows
(2, 64) matching rows
whoopsie
(2, 64) matching rows


 now
[80, 81, 84, 85, 8, 9, 26, 27, 170, 171, 142, 143, 146, 147, 176, 177, 32, 33, 92, 93, 38, 39, 6, 7, 90, 91, 30, 31, 106, 107, 96, 97, 156, 157, 62, 63, 4, 5, 48, 49, 22, 23, 172, 173, 78, 79, 68, 69, 152, 153, 122, 123, 136, 137]
90 54 36 lengths
126 54 36 lengths after add test to train
180 Cinical shape
{'train': 

0.9965531717374838 new standard
-0.008256181972084341 new mean
(90, 90) FEATS SHOULD BE HIGH
750
1.004784373312807 new standard
-0.06816082740092075 new mean
(90, 90) FEATS SHOULD BE HIGH
700
1.0377478641243638 new standard
-0.14436022312739352 new mean
(90, 90) FEATS SHOULD BE HIGH
655
1.0528101331233777 new standard
-0.12136386555745907 new mean
(90, 90) FEATS SHOULD BE HIGH
688
1.1368532687315784 new standard
0.2736225276772865 new mean
(90, 90) FEATS SHOULD BE HIGH
1143
1.0835368705212836 new standard
0.13818927074584214 new mean
(90, 90) FEATS SHOULD BE HIGH
917
1.140284373827531 new standard
0.05810120429388777 new mean
(90, 90) FEATS SHOULD BE HIGH
853
1.1350850826802836 new standard
0.06741870558670675 new mean
(90, 90) FEATS SHOULD BE HIGH
856
1.0176572588682529 new standard
0.07383582110393785 new mean
(90, 90) FEATS SHOULD BE HIGH
869
1.0072785176648362 new standard
-0.01934421221300122 new mean
(90, 90) FEATS SHOULD BE HIGH
769
1.0166992227059208 new standard
-0.02297515084

1.0324194010141388 new standard
0.11408136119402944 new mean
(90, 90) FEATS SHOULD BE HIGH
869
1.0629241794993196 new standard
0.17601627870305842 new mean
(90, 90) FEATS SHOULD BE HIGH
922
1.1466862212089703 new standard
0.20064117751972063 new mean
(90, 90) FEATS SHOULD BE HIGH
990
1.0892762678781032 new standard
0.40908493064224816 new mean
(90, 90) FEATS SHOULD BE HIGH
1246
1.0577402586447187 new standard
-0.05144499810643035 new mean
(90, 90) FEATS SHOULD BE HIGH
739
1.0478794739732153 new standard
0.03716841014222197 new mean
(90, 90) FEATS SHOULD BE HIGH
855
1.0971852812026168 new standard
0.05924961009536619 new mean
(90, 90) FEATS SHOULD BE HIGH
829
1.036433978666367 new standard
0.04436305329067003 new mean
(90, 90) FEATS SHOULD BE HIGH
808
1.0440221815679118 new standard
0.0431258315738219 new mean
(90, 90) FEATS SHOULD BE HIGH
834
1.0526638147096212 new standard
0.02499407871618166 new mean
(90, 90) FEATS SHOULD BE HIGH
830
1.04837976406744 new standard
0.08040924336730784 

[20, 21, 130, 131, 164, 165, 72, 73, 144, 145, 124, 125, 36, 37, 112, 113, 94, 95, 134, 135, 166, 167, 150, 151, 12, 13, 140, 141, 44, 45, 126, 127, 110, 111, 42, 43] SELF INDICES
['0', '1', '2', '3', '10', '11', '14', '15', '16', '17', '18', '19', '24', '25', '28', '29', '34', '35', '40', '41', '46', '47', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '64', '65', '66', '67', '70', '71', '74', '75', '76', '77', '82', '83', '86', '87', '88', '89', '98', '99', '100', '101', '102', '103', '104', '105', '108', '109', '114', '115', '116', '117', '118', '119', '120', '121', '128', '129', '132', '133', '138', '139', '148', '149', '154', '155', '158', '159', '160', '161', '162', '163', '168', '169', '174', '175', '178', '179', '4', '5', '6', '7', '8', '9', '22', '23', '26', '27', '30', '31', '32', '33', '38', '39', '48', '49', '62', '63', '68', '69', '78', '79', '80', '81', '84', '85', '90', '91', '92', '93', '96', '97', '106', '107', '122', '123', '136', '137', '142'

C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\130_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\125_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\37_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\126_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_p

torch.Size([91, 91]) SHAPE!!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\160_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\19_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\66_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
torch.Size([91, 91]) SHAPE!!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embedding

C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\116_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\109_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\10_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\132_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneD

C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\6_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\31_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\38_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\176_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats

C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\84_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\171_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\123_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\27_embeddings.csv SAVE EMBEDDINGS!
torch.Size([91, 91]) SHAPE!!
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pa

['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\3_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even 

(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\14_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
R

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\25_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\26_embe

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\36_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\37_embe

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\47_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\48_embe

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\58_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\59_embe

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\69_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\70_embe

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\80_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\81_embe

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\91_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\92_embe

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\102_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\103_em

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\113_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\114_em

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\124_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\125_em

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\135_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\136_em

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\146_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\147_em

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\157_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\158_em

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\168_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\169_em

['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
Reading Embedding: C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8\0\embeddings\179_embeddings.csv
3 NATURAL DIM
0.54 CCCCCCCC
[2 8 5 3 6 7 1 0 4]
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBNET LABELS
Functional Net LABEL
(54, 3) EMBEDDING SHAPE
['pDMN Pct', 'aDMN Pct', 'DAN Pct', 'FPN Pct', 'VN Pct', 'VAN Pct', 'SN Pct', 'SMN Pct'] subnet pct
(54, 35) EMB SHAPE
{0: 'pDMN', 1: 'aDMN', 2: 'DAN', 3: 'FPN', 4: 'VN', 5: 'VAN', 6: 'SN', 7: 'SMN'} SUBMEEEEEEEEEEEt
FEATES
still using binary weight, even though pcts used to make inclusion
['pDMN', 'aDMN', 'DAN', 'FPN', 'VN', 'VAN', 'SN', 'SMN'] ABESL
(180, 1) (180, 8)
     Scan Index  pDMN_Rad  aDMN_Rad   DAN_Rad   FPN_Rad    VN_Rad   VAN_Rad  \
0             0  1.172557  2.099933  2.249082  1.965658  1.169403  2.115446   
1             1

tensor([1.], dtype=torch.float64) layer of c 0
1.0 listed c
tensor([1.], dtype=torch.float64) layer of c 1
1.0 listed c
2.0 1.0 1.0
r t c
alpha BANDS
0 ID please?
1 PLV
0 graph norm?
{'train': [0, 1, 2, 3, 6, 7, 10, 11, 16, 17, 18, 19, 20, 21, 26, 27, 28, 29, 30, 31, 34, 35, 36, 37, 38, 39, 40, 41, 46, 47, 48, 49, 52, 53, 54, 55, 56, 57, 60, 61, 62, 63, 74, 75, 80, 81, 84, 85, 88, 89, 94, 95, 98, 99, 100, 101, 110, 111, 116, 117, 118, 119, 122, 123, 128, 129, 136, 137, 138, 139, 140, 141, 150, 151, 152, 153, 154, 155, 160, 161, 162, 163, 164, 165, 168, 169, 174, 175, 176, 177, 132, 133, 134, 135, 146, 147, 114, 115, 120, 121, 42, 43, 172, 173, 178, 179, 24, 25, 130, 131, 64, 65, 156, 157, 102, 103, 108, 109, 50, 51, 86, 87, 70, 71, 4, 5], 'valid': [124, 125, 66, 67, 148, 149, 8, 9, 142, 143, 166, 167, 92, 93, 90, 91, 78, 79, 12, 13, 68, 69, 104, 105, 22, 23, 72, 73, 126, 127, 112, 113, 106, 107, 32, 33, 96, 97, 170, 171, 144, 145, 76, 77, 44, 45, 14, 15, 158, 159, 82, 83, 58, 59], 'tes

tensor([0.4247], dtype=torch.float64) AVERAGE C
out stat dict
(180, 154) og shape
(180, 154) DF SHAPE
(180, 90) conccat
(180, 90) SHAPE
     Pre  Scan Index        ID  CogTr  diagnosis  pre_MMSE  pre_7MS  pre_BNT  \
0      1           0  UMEC-002      1          1      30.0     89.0     60.0   
1      0           1  UMEC-002      1          1      30.0     89.0     60.0   
2      1           2  UMEC-020      1          1      30.0     79.0      NaN   
3      0           3  UMEC-020      1          1      30.0     79.0      NaN   
4      1           4  UMEC-022      1          1      29.0     62.0     49.0   
..   ...         ...       ...    ...        ...       ...      ...      ...   
175    0         175  UMEC-213      2          2      29.0     73.0     57.0   
176    1         176  UMEC-214      2          2      30.0     89.0     54.0   
177    0         177  UMEC-214      2          2      30.0     89.0     54.0   
178    1         178  UMEC-216      2          2      30.0     7

tensor([0.3890], dtype=torch.float64) AVERAGE C
out stat dict
(180, 154) og shape
(180, 154) DF SHAPE
(180, 154) DF SHAPE
(180, 90) conccat
(180, 90) SHAPE
     Pre  Scan Index        ID  CogTr  diagnosis  pre_MMSE  pre_7MS  pre_BNT  \
0      1           0  UMEC-002      1          1      30.0     89.0     60.0   
1      0           1  UMEC-002      1          1      30.0     89.0     60.0   
2      1           2  UMEC-020      1          1      30.0     79.0      NaN   
3      0           3  UMEC-020      1          1      30.0     79.0      NaN   
4      1           4  UMEC-022      1          1      29.0     62.0     49.0   
..   ...         ...       ...    ...        ...       ...      ...      ...   
175    0         175  UMEC-213      2          2      29.0     73.0     57.0   
176    1         176  UMEC-214      2          2      30.0     89.0     54.0   
177    0         177  UMEC-214      2          2      30.0     89.0     54.0   
178    1         178  UMEC-216      2       