In [1]:
"""
This script can be used for recreating the link prediction results for different parameter settings
and dimensionality
"""
import argparse
from datetime import datetime
import random
import numpy as np
import os
import time
from utils import *
from params import *
# from params import BAND_TO_OPT_C
import sys
from datetime import date
import pickle
import train_inductive
# should we not make a seperate config for out "official runnings"
from trials.hyperparam_config import config
import pickle
import optuna
import copy
from utils.train_utils import get_dir_name, format_metrics
from main import parse_default_args
# import t
from hyperparam import create_study_output_dir,create_objective_fun,complete_study_one_arg
from utils.model_analysis_utils import save_embeddings_all
from data.MEG import get_data
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

imported utils


In [2]:
from trials.hyperparam_config import config
from main import parse_default_args

In [3]:
BAND_TO_OPT_C= { 
           'alpha':.54,
           'gamma':.66,
           'beta': .74,
            'theta':None
}

In [4]:
hyp_arch_dict={'model':'HGCN','optimizer':'RiemannianAdam','manifold':'PoincareBall'}
euc_arch_dict={'model':'GCN','optimizer':'Adam','manifold':'Euclidean'} 

In [5]:
arch_types={'full':{'use_weight':1,'use_virtual':1},
            'no_virt':{'use_weight':1,'use_virtual':0},
                'no_weight':{'use_weight':0,'use_virtual':1}}

input_types={'plv':{'use_plv':1,'use_identity':0,'num_feature':91},
             'id':{'use_plv':0,'use_identity':1,'num_feature':91},
             'id_plv':{'use_plv':1,'use_identity':1,'num_feature':181}}


curve_types={'setc':{**hyp_arch_dict,'c':'set'},
            'findc':{**hyp_arch_dict,'c':None},
            '1c':{**hyp_arch_dict,'c':1},
             'euc':{**euc_arch_dict,'c':0},
            }
curve_types

{'setc': {'model': 'HGCN',
  'optimizer': 'RiemannianAdam',
  'manifold': 'PoincareBall',
  'c': 'set'},
 'findc': {'model': 'HGCN',
  'optimizer': 'RiemannianAdam',
  'manifold': 'PoincareBall',
  'c': None},
 '1c': {'model': 'HGCN',
  'optimizer': 'RiemannianAdam',
  'manifold': 'PoincareBall',
  'c': 1},
 'euc': {'model': 'GCN', 'optimizer': 'Adam', 'manifold': 'Euclidean', 'c': 0}}

In [7]:
# the total number of validation runs that all should have
NUM_VALIDATIONS=3
criteria={'CogTr':1}
criteria={}
set_args={'dataset':'meg',
          'task':'lp',
          'val_sub':0,
          'lr':.015,
          'stretch_sigmoid':0,
          'plv_norm_w_id':0,
          'plv_inp_raw':0,
          'unify_pos_neg_loss':0,
          'stretch_sigmoid':0,
          'use_weighted_bce':0,
          'criteria_dict':criteria}
criteria=criteria
output_dims=[2]
arch_types_to_use=['full']
input_types_to_use=['id']
curve_types_to_use=['findc']
# raise Exception('OBVIOUSLY WE 'SHOULD ADD "CRITERIA INTO the folder name... dont want to mix those')
for d in output_dims:
    for i in input_types_to_use:
        inp_dict=input_types[i]
        for c_type in curve_types_to_use:
#             print(c,'C')
#             print(c_dict,'C DICT?')
            c_dict=curve_types[c_type]
#             print(c_dict,'')
            c_val=c_dict['c']
            print(c_val,'C VAL')
            if c_val=='set':
                c_set=BAND_TO_OPT_C['alpha']
                c_dict['c']=c_set
                
            set_args = copy.deepcopy(set_args)
            set_args['output_dim']=d
            set_args.update(c_dict)
            set_args.update(inp_dict)
            args = parse_default_args(set_args)
#             print(set_args['c'],set_args['use_identity'],set_args['use_plv'])
            print('compase')
            print('C: {}, ID: {}, PLV {}'.format(set_args['c'],set_args['use_identity'],set_args['use_plv']))
            print('C: {}, ID: {}, PLV {}'.format(args.c,args.use_identity,args.use_plv))
#             aka
            complete_study_one_arg(args,NUM_VALIDATIONS)
    
#             sksks
#             try:
#                 complete_study_one_arg(args,NUM_VALIDATIONS)
#             except:
#                 print('FUCKED THAT UP')
#             sksks
            
            

# # c=[1,None,.54]
# args = parse_default_args(set_args) ### still need to call this with args for dataset, possibly others
# complete_study_one_arg(args,NUM_VALIDATIONS)
# # print(args)
# # change_task(args,)

# # 
# # setattr(args,'criteria_dict',criteria)

INFO:root:Using: cpu


None C VAL
lp should match manual
lp 3
compase
C: None, ID: 1, PLV 0
C: None, ID: 1, PLV 0


HGCN_full_findc_id_dp model
HGCN_full_findc_id_dp model
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\april\all_pats\L2\HGCN_full_findc_id_dp\e100_p2fr5_lr0.015g0.9lf_10_strchinpvpct0.3_tpct0.2_95_bstrchloss95_lnmse_pn study dir
we are in here??
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\april\all_pats\L2\HGCN_full_findc_id_dp\e100_p2fr5_lr0.015g0.9lf_10_strchinpvpct0.3_tpct0.2_95_bstrchloss95_lnmse_pn study directory!
meg ARG DATASET
in here 
graph DATA NAME
Names            ['Left Precentral gyrus']
Nicknames                       ['lPreCG']
Index                                    0
X                                 -0.03893
Y                                -0.006961
Z                                  0.04964
Source Count                            32
DMN Pct                                0.0
pDMN Pct                               0.0
a

(180, 90, 90) RIGHTOUT DATA
0.3309338126375074 80
0.32764641825358093 79
0.32456669569015506 78
0.316118533987748 75
0.34999029636383056 85
0.37674931507844195 90
0.4264068635304769 95
dict_keys(['mm_strech', 'ms_norm', 'ms_sigmoid', 'identity', 'add_noise', 'pca_transform']) keys
parsing scans as graphs...
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
680
0.0 ADD NOISEessing: 0
(90, 90) FEATS SHOULD BE HIGH
692
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
606
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
535
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
916
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
670
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
842
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
793
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
936
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
875
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
869
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
812
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
776
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
798
0.0 ADD NO

(90, 90) FEATS SHOULD BE HIGH
748
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
739
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
855
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
705
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
729
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
739
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
794
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
651
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
695
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
762
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
914
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
799
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
810
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
883
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
941
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
838
0.0 ADD NOISE


INFO:root:LPModel(
  (encoder): HGCN(
    (layers): Sequential(
      (0): HyperbolicGraphConvolution(
        (linear): HypLinear(
          in_features=91, out_features=6, c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (agg): HypAgg(
          c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (hyp_act): HypAct(
          c_in=Parameter containing:
          tensor([1.], requires_grad=True), c_out=Parameter containing:
          tensor([1.], requires_grad=True)
        )
      )
      (1): HyperbolicGraphConvolution(
        (linear): HypLinear(
          in_features=6, out_features=2, c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (agg): HypAgg(
          c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
      )
    )
  )
  (dc): FermiDiracDecoder()
)
INFO:root:Total number of parameters: 571.0


(90, 90) FEATS SHOULD BE HIGH
872
test: 100 %      
180 unique ids
180 Final count
train SPLIT
True HAS TRAIN ONLY
0 USES TRAIN ONLY
[0, 1, 2, 3, 6, 7, 10, 11, 12, 13, 16, 17, 20, 21, 24, 25, 30, 31, 36, 37, 38, 39, 40, 41, 42, 43, 46, 47, 48, 49, 52, 53, 56, 57, 62, 63, 64, 65, 66, 67, 70, 71, 72, 73, 74, 75, 78, 79, 80, 81, 82, 83, 92, 93, 94, 95, 108, 109, 116, 117, 118, 119, 120, 121, 126, 127, 142, 143, 148, 149, 150, 151, 154, 155, 156, 157, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177] SELF INDICES
['0', '1', '2', '3', '6', '7', '10', '11', '12', '13', '16', '17', '20', '21', '24', '25', '30', '31', '36', '37', '38', '39', '40', '41', '42', '43', '46', '47', '48', '49', '52', '53', '56', '57', '62', '63', '64', '65', '66', '67', '70', '71', '72', '73', '74', '75', '78', '79', '80', '81', '82', '83', '92', '93', '94', '95', '108', '109', '116', '117', '118', '119', '120', '121', '126', '127', '142', '143', '148', '149', '150', '151', '154', '155', '156', '

C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\torch\autograd\__init__.py:199: UserWarning: Error detected in ReciprocalBackward0. Traceback of forward call that caused the error:
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
    app.start()
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
 

RuntimeError: Function 'ReciprocalBackward0' returned nan values in its 0th output.

In [ ]:
# the total number of validation runs that all should have
NUM_VALIDATIONS=3
criteria={'CogTr':1}
criteria={}
set_args={'dataset':'meg',
          'task':'lp',
          'val_sub':0,
          'lr':.01,
          'stretch_sigmoid':0,
          'plv_norm_w_id':0,
          'plv_inp_raw':0,
          'unify_pos_neg_loss':0,
          'stretch_sigmoid':0,
          'use_weighted_bce':0,
          'criteria_dict':criteria}
criteria=criteria
output_dims=[3]
arch_types_to_use=['full']
input_types_to_use=['id']
curve_types_to_use=['findc']
# raise Exception('OBVIOUSLY WE 'SHOULD ADD "CRITERIA INTO the folder name... dont want to mix those')
for d in output_dims:
    for i in input_types_to_use:
        inp_dict=input_types[i]
        for c_type in curve_types_to_use:
#             print(c,'C')
#             print(c_dict,'C DICT?')
            c_dict=curve_types[c_type]
#             print(c_dict,'')
            c_val=c_dict['c']
            print(c_val,'C VAL')
            if c_val=='set':
                c_set=BAND_TO_OPT_C['alpha']
                c_dict['c']=c_set
                
            set_args = copy.deepcopy(set_args)
            set_args['output_dim']=d
            set_args.update(c_dict)
            set_args.update(inp_dict)
            args = parse_default_args(set_args)
#             print(set_args['c'],set_args['use_identity'],set_args['use_plv'])
            print('compase')
            print('C: {}, ID: {}, PLV {}'.format(set_args['c'],set_args['use_identity'],set_args['use_plv']))
            print('C: {}, ID: {}, PLV {}'.format(args.c,args.use_identity,args.use_plv))
#             aka
            complete_study_one_arg(args,NUM_VALIDATIONS)
    
#             sksks
#             try:
#                 complete_study_one_arg(args,NUM_VALIDATIONS)
#             except:
#                 print('FUCKED THAT UP')
#             sksks
            
            

# # c=[1,None,.54]
# args = parse_default_args(set_args) ### still need to call this with args for dataset, possibly others
# complete_study_one_arg(args,NUM_VALIDATIONS)
# # print(args)
# # change_task(args,)

# # 
# # setattr(args,'criteria_dict',criteria)

In [ ]:
model = LPModel({})

In [ ]:

# the total number of validation runs that all should have
NUM_VALIDATIONS=2
criteria={'CogTr':1}
set_args={'dataset':'meg',
          'task':'lp',
          'val_sub':1,
          'epochs':50,
          'stretch_sigmoid':0,
          'criteria_dict':criteria}
criteria=criteria
output_dims=[3]
arch_types_to_use=['full']
input_types_to_use=['plv']
curve_types_to_use=['setc']
# raise Exception('OBVIOUSLY WE SHOULD ADD "CRITERIA INTO the folder name... dont want to mix those')
for d in output_dims:
    for i in input_types_to_use:
        inp_dict=input_types[i]
        for c_type in curve_types_to_use:
#             print(c,'C')
#             print(c_dict,'C DICT?')
            c_dict=curve_types[c_type]
#             print(c_dict,'')
            c_val=c_dict['c']
            print(c_val,'C VAL')
            if c_val=='set':
                c_set=BAND_TO_OPT_C['alpha']
                c_dict['c']=c_set
                
            set_args = copy.deepcopy(set_args)
            set_args['output_dim']=d
            set_args.update(c_dict)
            set_args.update(inp_dict)
            args = parse_default_args(set_args)
#             print(set_args['c'],set_args['use_identity'],set_args['use_plv'])
            print('compase')
            print('C: {}, ID: {}, PLV {}'.format(set_args['c'],set_args['use_identity'],set_args['use_plv']))
            print('C: {}, ID: {}, PLV {}'.format(args.c,args.use_identity,args.use_plv))
#             aka
            complete_study_one_arg(args,NUM_VALIDATIONS)
    
#             sksks
#             try:
#                 complete_study_one_arg(args,NUM_VALIDATIONS)
#             except:
#                 print('FUCKED THAT UP')
#             sksks
            
            

# # c=[1,None,.54]
# args = parse_default_args(set_args) ### still need to call this with args for dataset, possibly others
# complete_study_one_arg(args,NUM_VALIDATIONS)
# # print(args)
# # change_task(args,)
# # 
# # setattr(args,'criteria_dict',criteria)