In [61]:
"""
This script can be used for recreating the link prediction results for different parameter settings
and dimensionality
"""
import argparse
from datetime import datetime
import random
import numpy as np
import os
import time
from utils import *
from params import *
from params import MEGLpParams
# from params import BAND_TO_OPT_C
import sys
from datetime import date
import pickle
import train_inductive
# should we not make a seperate config for out "official runnings"
from trials.hyperparam_config import config
import pickle
import optuna
import copy
from utils.train_utils import get_dir_name, format_metrics
from utils.model_analysis_utils import plot_loss_dir,create_res_df_study
from main import parse_default_args
from hyperparam import create_study_output_dir,create_objective_fun,complete_study_one_arg
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [62]:
from trials.hyperparam_config import config
from main import parse_default_args

In [63]:
BAND_TO_OPT_C= { 
           'alpha':.54,
           'gamma':.66,
           'beta': .74,
            'theta':None
}

In [64]:
hyp_arch_dict={'model':'HGCN','optimizer':'RiemannianAdam','manifold':'PoincareBall'}
euc_arch_dict={'model':'GCN','optimizer':'Adam','manifold':'Euclidean'} 

In [65]:
arch_types={'full':{'use_weight':1,'use_virtual':1},
            'no_virt':{'use_weight':1,'use_virtual':0},
                'no_weight':{'use_weight':0,'use_virtual':1}}

input_types={'plv':{'use_plv':1,'use_identity':0,'num_feature':91},
             'id':{'use_plv':0,'use_identity':1,'num_feature':91},
             'id_plv':{'use_plv':1,'use_identity':1,'num_feature':181}}

curve_types={'setc':{**hyp_arch_dict,'c':'set'},
            'findc':{**hyp_arch_dict,'c':None},
            '1c':{**hyp_arch_dict,'c':1},
             'euc':{**euc_arch_dict,'c':0},
            }
curve_types

{'setc': {'model': 'HGCN',
  'optimizer': 'RiemannianAdam',
  'manifold': 'PoincareBall',
  'c': 'set'},
 'findc': {'model': 'HGCN',
  'optimizer': 'RiemannianAdam',
  'manifold': 'PoincareBall',
  'c': None},
 '1c': {'model': 'HGCN',
  'optimizer': 'RiemannianAdam',
  'manifold': 'PoincareBall',
  'c': 1},
 'euc': {'model': 'GCN', 'optimizer': 'Adam', 'manifold': 'Euclidean', 'c': 0}}

In [66]:
# the total number of validation runs that all should have
NUM_VALIDATIONS=4
criteria={'CogTr':1}
set_args={'dataset':'meg',
          'task':'lp',
          'val_sub':1,
          'stretch_sigmoid':0,
          'plv_norm_w_id':0,
          'plv_inp_raw':0,
          'unify_pos_neg_loss':0,
          'stretch_sigmoid':0,
          'use_weighted_bce':0,
          'criteria_dict':criteria}
criteria=criteria
output_dims=[3,4,2]
arch_types_to_use=['full']
input_types_to_use=['id']
curve_types_to_use=['findc']
# raise Exception('OBVIOUSLY WE 'SHOULD ADD "CRITERIA INTO the folder name... dont want to mix those')
for d in output_dims:
    for i in input_types_to_use:
        inp_dict=input_types[i]
        for c_type in curve_types_to_use:
#             print(c,'C')
#             print(c_dict,'C DICT?')
            c_dict=curve_types[c_type]
#             print(c_dict,'')
            c_val=c_dict['c']
            print(c_val,'C VAL')
            if c_val=='set':
                c_set=BAND_TO_OPT_C['alpha']
                c_dict['c']=c_set
                
            set_args = copy.deepcopy(set_args)
            set_args['output_dim']=d
            set_args.update(c_dict)
            set_args.update(inp_dict)
            args = parse_default_args(set_args)
#             print(set_args['c'],set_args['use_identity'],set_args['use_plv'])
            print('compase')
            print('C: {}, ID: {}, PLV {}'.format(set_args['c'],set_args['use_identity'],set_args['use_plv']))
            print('C: {}, ID: {}, PLV {}'.format(args.c,args.use_identity,args.use_plv))
#             aka
            complete_study_one_arg(args,NUM_VALIDATIONS)
    
#             sksks
#             try:
#                 complete_study_one_arg(args,NUM_VALIDATIONS)
#             except:
#                 print('FUCKED THAT UP')
#             sksks
            
            

# # c=[1,None,.54]
# args = parse_default_args(set_args) ### still need to call this with args for dataset, possibly others
# complete_study_one_arg(args,NUM_VALIDATIONS)
# # print(args)
# # change_task(args,)

# # 
# # setattr(args,'criteria_dict',criteria)

INFO:root:Using: cpu


None C VAL
lp should match manual
lp 3
compase
C: None, ID: 1, PLV 0
C: None, ID: 1, PLV 0


HGCN_full_findc_id_dp model
HGCN_full_findc_id_dp model
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\test\pats_CogTr1\L3\HGCN_full_findc_id_dp\e70_p6fr2_lr0.021_val_excl_group_strchinp95_strchloss95_b8_lmse_pneq study dir
True exists for sure
['0', '1']
we are in here??
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\test\pats_CogTr1\L3\HGCN_full_findc_id_dp\e70_p6fr2_lr0.021_val_excl_group_strchinp95_strchloss95_b8_lmse_pneq study directory!
<class 'models.base_models.LPModel'>
<class 'models.base_models.LPModel'>
<class 'models.encoders.HGCN'> aTTRs
91 NUMBER FEATs
[91, 6] dims
[91, 6, 3] dims after
[91, 6, 3] dims
[<function selu at 0x000001681F179048>, <function selu at 0x000001681F179048>] acts
[True, False] uise acts
gn NORMAL TYPE
True USE AGG
frechet agg True
gn NORMAL TYPE
True USE AGG
frechet agg True
no pruner
no trial
meg ARG DATASE

(180, 90, 90) RIGHTOUT DATA
0.3309338126375074 80
0.32764641825358093 79
0.32456669569015506 78
0.316118533987748 75
0.34999029636383056 85
0.37674931507844195 90
0.4264068635304769 95
dict_keys(['mm_strech', 'ms_norm', 'ms_sigmoid', 'identity', 'add_noise', 'pca_transform']) keys
parsing scans as graphs...
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
680
0.0 ADD NOISEessing: 0
(90, 90) FEATS SHOULD BE HIGH
692
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
606
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
535
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
801
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
788
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
916
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
670
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
879
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
798
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
842
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
793
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
936
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
875
0.0 ADD NO

(90, 90) FEATS SHOULD BE HIGH
838
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
872
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
921
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
558
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
696
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
556
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
706
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
721
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
854
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
854
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
916
0.0 ADD NOISE


INFO:root:LPModel(
  (encoder): HGCN(
    (layers): Sequential(
      (0): HyperbolicGraphConvolution(
        (linear): HypLinear(
          in_features=91, out_features=6, c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (agg): HypAgg(
          c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (hyp_act): HypAct(
          c_in=Parameter containing:
          tensor([1.], requires_grad=True), c_out=Parameter containing:
          tensor([1.], requires_grad=True)
        )
      )
      (1): HyperbolicGraphConvolution(
        (linear): HypLinear(
          in_features=6, out_features=3, c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (agg): HypAgg(
          c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
      )
    )
  )
  (dc): FermiDiracDecoder()
)
INFO:root:Total number of parameters: 578.0


(90, 90) FEATS SHOULD BE HIGH
859
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
676
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
759
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
724
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
663
test: 100 %      
180 unique ids
180 Final count
train SPLIT
True HAS TRAIN ONLY
0 USES TRAIN ONLY
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91] SELF INDICES
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', 

2.0 1.0 FERMI epoch: 0
Parameter containing:
tensor([1.], requires_grad=True) MODEL C
reset
92 train length
23
train phase of epoch 0: precision 0.635630,roc 0.842009, loss 0.441283, acc 0, ECE 0 #edges 92115, #graphs 23
46
train phase of epoch 0: precision 0.650212,roc 0.827686, loss 0.373632, acc 0, ECE 0 #edges 184230, #graphs 46
69
train phase of epoch 0: precision 0.663094,roc 0.837136, loss 0.324695, acc 0, ECE 0 #edges 276345, #graphs 69


INFO:root:Epoch: 0001 lr: 0.021 train phase of epoch 0: precision 0.670405,roc 0.851307, loss 0.273571, acc 0, ECE 0 #edges 368460, #graphs 92 time: 157.7226s


92
train phase of epoch 0: precision 0.670405,roc 0.851307, loss 0.273571, acc 0, ECE 0 #edges 368460, #graphs 92
92
2.0 1.0 FERMI epoch: 1
Parameter containing:
tensor([1.3323], requires_grad=True) MODEL C
92
reset
92 train length
23
train phase of epoch 1: precision 0.730691,roc 0.907586, loss 0.116603, acc 0, ECE 0 #edges 92115, #graphs 23
46
train phase of epoch 1: precision 0.745232,roc 0.910857, loss 0.113102, acc 0, ECE 0 #edges 184230, #graphs 46
69
train phase of epoch 1: precision 0.746173,roc 0.911988, loss 0.109178, acc 0, ECE 0 #edges 276345, #graphs 69


INFO:root:Epoch: 0002 lr: 0.021 train phase of epoch 1: precision 0.750668,roc 0.914498, loss 0.104768, acc 0, ECE 0 #edges 368460, #graphs 92 time: 192.6963s


92
train phase of epoch 1: precision 0.750668,roc 0.914498, loss 0.104768, acc 0, ECE 0 #edges 368460, #graphs 92
92
training epoch done in  time: 192.6963s
92
17
0.09328385610601812 0.8723066754791804 loss acc
17
0.09328385610601812 0.8723066754791804 loss acc


INFO:root:Dev Epoch: 0002 dev phase of epoch 1: precision 0.777550,roc 0.921615, loss 0.093284, acc 0, ECE 0 #edges 68085, #graphs 17
INFO:root:Saved model in C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\test\pats_CogTr1\L3\HGCN_full_findc_id_dp\e70_p6fr2_lr0.021_val_excl_group_strchinp95_strchloss95_b8_lmse_pneq\2


71
2.0 1.0 FERMI epoch: 2
Parameter containing:
tensor([1.3018], requires_grad=True) MODEL C
71
reset
92 train length


C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\torch\autograd\__init__.py:199: UserWarning: Error detected in FrechetMeanBackward. Traceback of forward call that caused the error:
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
    app.start()
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
 

KeyboardInterrupt: 

In [60]:
# the total number of validation runs that all should have
NUM_VALIDATIONS=2
criteria={'CogTr':1}

set_args={'dataset':'meg',
          'task':'lp',
          'val_sub':1,
          'stretch_sigmoid':0,
          'plv_norm_w_id':0,
          'plv_inp_raw':0,
          'unify_pos_neg_loss':0,
          'stretch_sigmoid':0,
          'use_weighted_bce':0,
          'criteria_dict':criteria}

criteria=criteria
output_dims=[3,4,2]
arch_types_to_use=['full']
input_types_to_use=['id']
curve_types_to_use=['findc']
# raise Exception('OBVIOUSLY WE 'SHOULD ADD "CRITERIA INTO the folder name... dont want to mix those')
for d in output_dims:
    for i in input_types_to_use:
        inp_dict=input_types[i]
        for c_type in curve_types_to_use:
#             print(c,'C')
#             print(c_dict,'C DICT?')
            c_dict=curve_types[c_type]
#             print(c_dict,'')
            c_val=c_dict['c']
            print(c_val,'C VAL')
            if c_val=='set':
                c_set=BAND_TO_OPT_C['alpha']
                c_dict['c']=c_set
                
            set_args = copy.deepcopy(set_args)
            set_args['output_dim']=d
            set_args.update(c_dict)
            set_args.update(inp_dict)
            args = parse_default_args(set_args)
#             print(set_args['c'],set_args['use_identity'],set_args['use_plv'])
            print('compase')
            print('C: {}, ID: {}, PLV {}'.format(set_args['c'],set_args['use_identity'],set_args['use_plv']))
            print('C: {}, ID: {}, PLV {}'.format(args.c,args.use_identity,args.use_plv))
#             aka
            complete_study_one_arg(args,NUM_VALIDATIONS)
    
#             sksks
#             try:
#                 complete_study_one_arg(args,NUM_VALIDATIONS)
#             except:
#                 print('FUCKED THAT UP')
#             sksks
            
            

# # c=[1,None,.54]
# args = parse_default_args(set_args) ### still need to call this with args for dataset, possibly others
# complete_study_one_arg(args,NUM_VALIDATIONS)
# # print(args)
# # change_task(args,)

# # 
# # setattr(args,'criteria_dict',criteria)

INFO:root:Using: cpu


None C VAL
lp should match manual
lp 3
compase
C: None, ID: 1, PLV 0
C: None, ID: 1, PLV 0


HGCN_full_findc_id_dp model
HGCN_full_findc_id_dp model
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\test\pats_CogTr1\L3\HGCN_full_findc_id_dp\e70_p6fr2_lr0.021_val_excl_group_strchinp95_strchloss95_b8_lmse_pneq study dir
True exists for sure
['0']
we are in here??
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\test\pats_CogTr1\L3\HGCN_full_findc_id_dp\e70_p6fr2_lr0.021_val_excl_group_strchinp95_strchloss95_b8_lmse_pneq study directory!
<class 'models.base_models.LPModel'>
<class 'models.base_models.LPModel'>
<class 'models.encoders.HGCN'> aTTRs
91 NUMBER FEATs
[91, 6] dims
[91, 6, 3] dims after
[91, 6, 3] dims
[<function selu at 0x000001681F179048>, <function selu at 0x000001681F179048>] acts
[True, False] uise acts
gn NORMAL TYPE
True USE AGG
frechet agg True
gn NORMAL TYPE
True USE AGG
frechet agg True
no pruner
no trial
meg ARG DATASET
in 

(180, 90, 90) RIGHTOUT DATA
0.3309338126375074 80
0.32764641825358093 79
0.32456669569015506 78
0.316118533987748 75
0.34999029636383056 85
0.37674931507844195 90
0.4264068635304769 95
dict_keys(['mm_strech', 'ms_norm', 'ms_sigmoid', 'identity', 'add_noise', 'pca_transform']) keys
parsing scans as graphs...
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
680
0.0 ADD NOISEessing: 0
(90, 90) FEATS SHOULD BE HIGH
692
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
606
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
535
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
801
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
788
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
916
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
670
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
879
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
798
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
842
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
793
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
936
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
875
0.0 ADD NO

(90, 90) FEATS SHOULD BE HIGH
1116
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
921
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
558
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
556
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
654
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
721
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
854
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
854
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
916
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
669
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
859
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
676
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
759
0.0 ADD NOISE


INFO:root:LPModel(
  (encoder): HGCN(
    (layers): Sequential(
      (0): HyperbolicGraphConvolution(
        (linear): HypLinear(
          in_features=91, out_features=6, c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (agg): HypAgg(
          c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (hyp_act): HypAct(
          c_in=Parameter containing:
          tensor([1.], requires_grad=True), c_out=Parameter containing:
          tensor([1.], requires_grad=True)
        )
      )
      (1): HyperbolicGraphConvolution(
        (linear): HypLinear(
          in_features=6, out_features=3, c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (agg): HypAgg(
          c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
      )
    )
  )
  (dc): FermiDiracDecoder()
)
INFO:root:Total number of parameters: 578.0


(90, 90) FEATS SHOULD BE HIGH
724
0.0 ADD NOISE
(90, 90) FEATS SHOULD BE HIGH
663
test: 100 %      
180 unique ids
180 Final count
train SPLIT
True HAS TRAIN ONLY
0 USES TRAIN ONLY
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91] SELF INDICES
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', 

23
train phase of epoch 0: precision 0.588486,roc 0.835949, loss 0.507406, acc 0, ECE 0 #edges 92115, #graphs 23
46
train phase of epoch 0: precision 0.615658,roc 0.847889, loss 0.523021, acc 0, ECE 0 #edges 184230, #graphs 46
69
train phase of epoch 0: precision 0.619583,roc 0.845670, loss 0.494032, acc 0, ECE 0 #edges 276345, #graphs 69


INFO:root:Epoch: 0001 lr: 0.021 train phase of epoch 0: precision 0.611193,roc 0.837936, loss 0.425786, acc 0, ECE 0 #edges 368460, #graphs 92 time: 156.9757s


92
train phase of epoch 0: precision 0.611193,roc 0.837936, loss 0.425786, acc 0, ECE 0 #edges 368460, #graphs 92
92
2.0 1.0 FERMI epoch: 1
Parameter containing:
tensor([1.4108], requires_grad=True) MODEL C
92
reset
92 train length
23
train phase of epoch 1: precision 0.615321,roc 0.840792, loss 0.172310, acc 0, ECE 0 #edges 92115, #graphs 23
46
train phase of epoch 1: precision 0.640709,roc 0.851576, loss 0.162564, acc 0, ECE 0 #edges 184230, #graphs 46


C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\torch\autograd\__init__.py:199: UserWarning: Error detected in FrechetMeanBackward. Traceback of forward call that caused the error:
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
    app.start()
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "C:\Users\coleb\anaconda3\envs\hgcn_test\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
 

KeyboardInterrupt: 

In [3]:
root_ds= r'C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\ds'

In [1]:
# the total number of validation runs that all should have
NUM_VALIDATIONS=1
criteria={'CogTr':1}
# criteria={}
set_args={'dataset':'meg',
          'task':'lp',
          'criteria_dict':criteria,'epochs':80}

criteria=criteria
output_dims=[3]
arch_types_to_use=['full']
input_types_to_use=['plv']
curve_types_to_use=['findc']
#NOT SUSTAINABLE
stretch_pcts=[95]

for d in output_dims:
    for i in input_types_to_use:
        inp_dict=input_types[i]
        for c_type in curve_types_to_use:
#             print(c,'C')
#             print(c_dict,'C DICT?')

            c_dict=curve_types[c_type]
#             print(c_dict,'')
            c_val=c_dict['c']
            print(c_val,'C VAL')
            if c_val=='set':
                c_set=BAND_TO_OPT_C['alpha']
                c_dict['c']=c_set
                
            set_args = copy.deepcopy(set_args)
            set_args['output_dim']=d
            set_args.update(c_dict)
            set_args.update(inp_dict)
            
#             print(set_args['c'],set_args['use_identity'],set_args['use_plv'])
            print('compase')
            print('C: {}, ID: {}, PLV {}'.format(set_args['c'],set_args['use_identity'],set_args['use_plv']))
            print('C: {}, ID: {}, PLV {}'.format(args.c,args.use_identity,args.use_plv))
            for s in stretch_pcts:
                set_args['stretch_pct']=s
                args = parse_default_args(set_args)
                complete_study_one_arg(args,NUM_VALIDATIONS)


NameError: name 'input_types' is not defined

In [52]:
for (root,dirs,files) in os.walk(root_ds, topdown=True):
    print('NEXT LEVEL??')
#     print(root,dirs,files)
    if not dirs :
        continue
    embedding_roots=[]
#     full_dirs=p
#         os.path.join(s,r) for r in os.listdir(s) if '.csv' not in r  and ('.json' not in r) ]
    for d in dirs:
        full_dir=os.path.join(root,d)
        subfiles=os.listdir(full_dir)
        if ('finish_train.txt' in subfiles) or ('model.pth' in subfiles):
            embedding_roots.append(full_dir)
    if embedding_roots:
        print(root,embedding_roots)
            

NameError: name 'root_ds' is not defined

In [ ]:
root_ds= r'C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\ds\'

In [ ]:
root_ds=r'C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\all_pats\L3\HGCN_full_0.54c_plv_dp\e100_p10_lr0.021_vpct0.3_tpct0.2_stretch98_b8'

In [ ]:
create_res_df_study(root_ds)