In [59]:
"""
This script can be used for recreating the link prediction results for different parameter settings
and dimensionality
"""
import argparse
from datetime import datetime
import random
import numpy as np
import os
import time
from utils import *
from params import *
import sys
from datetime import date
import pickle
import train_inductive
# should we not make a seperate config for out "official runnings"
from trials.hyperparam_config import config
import pickle
import optuna
import copy
from utils.train_utils import get_dir_name, format_metrics
from main import parse_default_args
from hyperparam import create_study_output_dir,create_objective_fun,complete_study_one_arg
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [48]:
from trials.hyperparam_config import config
from main import parse_default_args

In [49]:
BAND_TO_OPT_C= { 
           'alpha':.54,
           'gamma':.66,
           'beta': .74,
            'theta':None
}

In [50]:
hyp_arch_dict={'model':'HGCN','optimizer':'RiemannianAdam','manifold':'PoincareBall'}
euc_arch_dict={'model':'GCN','optimizer':'Adam','manifold':'Euclidean'}

In [52]:
mod_types={'full':{'use_weight':1,'use_virtual':1},
            'no_virt':{'use_weight':1,'use_virtual':0},
                'no_weight':{'use_weight':0,'use_virtual':1}}

input_types={'plv':{'use_plv':1,'use_identity':0},'id':{'use_plv':0,'use_identity':1}}


curve_types={'setc':{**hyp_arch_dict,'c':'set'},
            'findc':{**hyp_arch_dict,'c':None},
            '1c':{**hyp_arch_dict,'c':1},
             'euc':{**euc_arch_dict,'c':0}}

In [ ]:
# the total number of validation runs that all should have
NUM_VALIDATIONS=2
criteria={'CogTr':1}
set_args={'dataset':'meg',
          'task':'lp',
          'criteria_dict':{}}
criteria=criteria
output_dims=[2,3,4]
mod_types_to_use=['full','no_virt','no_weight']
input_types_to_use=['id']
curve_types_to_use=['findc','1c','euc']
best=set(['full','findc','id'])
for d in output_dims:
    for i in input_types_to_use:
        inp_dict=input_types[i]
        inf_inp=0 if (i in best) else 1
        for c_type in curve_types_to_use:
            inf_c=0 if (c_type in best) else 1
#             print(c,'C')
#             print(c_dict,'C DICT?')
            c_dict=curve_types[c_type]
#             print(c_dict,'')
            c_val=c_dict['c']
            print(c_val,'C VAL')
#             if not inf_c:
#                 print(c,'c!!')
#                 sksks
            if c_val=='set':
                c_set=BAND_TO_OPT_C['alpha']
                c_dict['c']=c_set
                
            for m in mod_types_to_use:
                mod_dict=mod_types[m]
                inf_m=0 if (m in best) else 1
                if inf_m+inf_c>1:
                    continue
            
                
                set_args = copy.deepcopy(set_args)
                set_args['output_dim']=d
                set_args.update(c_dict)
                set_args.update(mod_dict)
                set_args.update(inp_dict)
                args = parse_default_args(set_args)
                print(args.criteria_dict)
                complete_study_one_arg(args,NUM_VALIDATIONS)
            
            

# # c=[1,None,.54]
# args = parse_default_args(set_args) ### still need to call this with args for dataset, possibly others
# complete_study_one_arg(args,NUM_VALIDATIONS)
# # print(args)
# # change_task(args,)
# # 
# # setattr(args,'criteria_dict',criteria)

INFO:root:Using: cpu
INFO:root:Using seed 1234.


None C VAL
lp should match manual
lp 3
{}
HGCN_full_findc_id_dp model
HGCN_full_findc_id_dp model
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\L2\HGCN_full_findc_id_dp study dir
meg ARG DATASET
in here 
graph DATA NAME
Unnamed: 0                               0
Names            ['Left Precentral gyrus']
Nicknames                       ['lPreCG']
Index                                    0
X                                 -0.03893
Y                                -0.006961
Z                                  0.04964
Source Count                            32
DMN Pct                                0.0
pDMN Pct                               0.0
aDMN Pct                               0.0
DAN Pct                             0.3125
FPN Pct                            0.09375
VN Pct                                 0.0
VAN Pct                             0.5625
SN Pct                                 0.0
SMN Pct                             0.1875
DMN Rank               

(90, 90) FEATS SHOULD BE HIGH
680
(90, 90) FEATS SHOULD BE HIGH
692
(90, 90) FEATS SHOULD BE HIGH
606
(90, 90) FEATS SHOULD BE HIGH
535
(90, 90) FEATS SHOULD BE HIGH
801
(90, 90) FEATS SHOULD BE HIGH
788
(90, 90) FEATS SHOULD BE HIGH
916
(90, 90) FEATS SHOULD BE HIGH
670
(90, 90) FEATS SHOULD BE HIGH
879
(90, 90) FEATS SHOULD BE HIGH
798
(90, 90) FEATS SHOULD BE HIGH
842
(90, 90) FEATS SHOULD BE HIGH
793
(90, 90) FEATS SHOULD BE HIGH
936
(90, 90) FEATS SHOULD BE HIGH
875
(90, 90) FEATS SHOULD BE HIGH
629
(90, 90) FEATS SHOULD BE HIGH
606
(90, 90) FEATS SHOULD BE HIGH
869
(90, 90) FEATS SHOULD BE HIGH
812
(90, 90) FEATS SHOULD BE HIGH
655
(90, 90) FEATS SHOULD BE HIGH
719
(90, 90) FEATS SHOULD BE HIGH
776
(90, 90) FEATS SHOULD BE HIGH
798
(90, 90) FEATS SHOULD BE HIGH
745
(90, 90) FEATS SHOULD BE HIGH
743
(90, 90) FEATS SHOULD BE HIGH
646
(90, 90) FEATS SHOULD BE HIGH
775
(90, 90) FEATS SHOULD BE HIGH
757
(90, 90) FEATS SHOULD BE HIGH
537
(90, 90) FEATS SHOULD BE HIGH
958
(90, 90) FEATS

INFO:root:LPModel(
  (encoder): HGCN(
    (layers): Sequential(
      (0): HyperbolicGraphConvolution(
        (linear): HypLinear(
          in_features=91, out_features=6, c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (agg): HypAgg(
          c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (hyp_act): HypAct(
          c_in=Parameter containing:
          tensor([1.], requires_grad=True), c_out=Parameter containing:
          tensor([1.], requires_grad=True)
        )
      )
      (1): HyperbolicGraphConvolution(
        (linear): HypLinear(
          in_features=6, out_features=2, c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (agg): HypAgg(
          c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
      )
    )
  )
  (dc): FermiDiracDecoder()
)
INFO:root:Total number of parameters: 571.0


[100, 101] SELF INDICES
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '66', '67', '68', '69', '70', '71', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '88', '89', '90', '91', '92', '93', '94', '95', '98', '99', '104', '105', '110', '111', '112', '113', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '150', '151', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '176', '177', '178', '179', '26', '27', '28', '29', '42', '43', '44', '45', '64', '65', '72', '73', '86

C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\manifolds\poincare.py:120: UserWarning: where received a uint8 condition tensor. This behavior is deprecated and will be removed in a future version of PyTorch. Use a boolean condition instead. (Triggered internally at  ..\aten\src\ATen\native\TensorCompare.cpp:328.)
  res = torch.where(cond, res_0, res_c)
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\optimizers\radam.py:126: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  ..\torch\csrc\utils\python_arg_parser.cpp:1050.)
  grad.add_(weight_decay, point)


23
train phase of epoch 0: precision 0.512657,roc 0.831872, loss 0.380438, acc 0, ECE 0 #edges 92115, #graphs 23
46
train phase of epoch 0: precision 0.516640,roc 0.844645, loss 0.271892, acc 0, ECE 0 #edges 184230, #graphs 46
69
train phase of epoch 0: precision 0.538312,roc 0.856578, loss 0.226430, acc 0, ECE 0 #edges 276345, #graphs 69
92
train phase of epoch 0: precision 0.564582,roc 0.867607, loss 0.198379, acc 0, ECE 0 #edges 368460, #graphs 92
115
train phase of epoch 0: precision 0.589142,roc 0.877224, loss 0.178760, acc 0, ECE 0 #edges 460575, #graphs 115
138
train phase of epoch 0: precision 0.608305,roc 0.885010, loss 0.164251, acc 0, ECE 0 #edges 552690, #graphs 138


INFO:root:Epoch: 0001 lr: 0.021 train phase of epoch 0: precision 0.614251,roc 0.886881, loss 0.161017, acc 0, ECE 0 #edges 576720, #graphs 144 time: 231.1126s


144
training epoch done in  time: 231.1126s
144
36
0.08843836353252629 0.8459009571369123 loss acc
36
0.08843836353252629 0.8459009571369123 loss acc


INFO:root:Dev Epoch: 0001 dev phase of epoch 0: precision 0.717823,roc 0.926886, loss 0.088438, acc 0, ECE 0 #edges 144180, #graphs 36
INFO:root:Test Epoch: 0001 test phase of epoch 0: precision 0.736990,roc 0.924339, loss 0.086415, acc 0, ECE 0 #edges 8010, #graphs 2
INFO:root:Saved model in C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\L2\HGCN_full_findc_id_dp\0


2
2.0 1.0 FERMI (non-adjusting) epoch: 1 LR:  [0.021]
Parameter containing:
tensor([1.0483], requires_grad=True) MODEL C
2
reset
144 train length
23
train phase of epoch 1: precision 0.714771,roc 0.930551, loss 0.090898, acc 0, ECE 0 #edges 92115, #graphs 23
46
train phase of epoch 1: precision 0.731001,roc 0.934194, loss 0.084901, acc 0, ECE 0 #edges 184230, #graphs 46
69
train phase of epoch 1: precision 0.740440,roc 0.937042, loss 0.081935, acc 0, ECE 0 #edges 276345, #graphs 69
92
train phase of epoch 1: precision 0.751460,roc 0.939683, loss 0.079490, acc 0, ECE 0 #edges 368460, #graphs 92
115
train phase of epoch 1: precision 0.758660,roc 0.941904, loss 0.077068, acc 0, ECE 0 #edges 460575, #graphs 115
138
train phase of epoch 1: precision 0.763336,roc 0.943511, loss 0.075593, acc 0, ECE 0 #edges 552690, #graphs 138


INFO:root:Epoch: 0002 lr: 0.021 train phase of epoch 1: precision 0.765292,roc 0.943890, loss 0.075105, acc 0, ECE 0 #edges 576720, #graphs 144 time: 220.3632s


144
training epoch done in  time: 220.3632s
144
36
0.06719289468662662 0.8696351782494104 loss acc
36
0.06719289468662662 0.8696351782494104 loss acc


INFO:root:Dev Epoch: 0002 dev phase of epoch 1: precision 0.792011,roc 0.950847, loss 0.067193, acc 0, ECE 0 #edges 144180, #graphs 36
INFO:root:Test Epoch: 0002 test phase of epoch 1: precision 0.815540,roc 0.952694, loss 0.068381, acc 0, ECE 0 #edges 8010, #graphs 2
INFO:root:Saved model in C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\L2\HGCN_full_findc_id_dp\0


2
2.0 1.0 FERMI (non-adjusting) epoch: 2 LR:  [0.021]
Parameter containing:
tensor([0.9627], requires_grad=True) MODEL C
2
reset
144 train length
23
train phase of epoch 2: precision 0.800696,roc 0.953107, loss 0.065829, acc 0, ECE 0 #edges 92115, #graphs 23
46
train phase of epoch 2: precision 0.798776,roc 0.953654, loss 0.065813, acc 0, ECE 0 #edges 184230, #graphs 46
69
train phase of epoch 2: precision 0.797904,roc 0.954430, loss 0.065581, acc 0, ECE 0 #edges 276345, #graphs 69
92
train phase of epoch 2: precision 0.800524,roc 0.954486, loss 0.065186, acc 0, ECE 0 #edges 368460, #graphs 92
115
train phase of epoch 2: precision 0.800074,roc 0.954698, loss 0.065399, acc 0, ECE 0 #edges 460575, #graphs 115
