In [2]:
"""
This script can be used for recreating the link prediction results for different parameter settings
and dimensionality
"""
import argparse
from datetime import datetime
import random
import numpy as np
import os
import time
from utils import *
from params import *
# from params import BAND_TO_OPT_C
import sys
from datetime import date
import pickle
import train_inductive
# should we not make a seperate config for out "official runnings"
from trials.hyperparam_config import config
import pickle
import optuna
import copy
from utils.train_utils import get_dir_name, format_metrics
from main import parse_default_args
from hyperparam import create_study_output_dir,create_objective_fun,complete_study_one_arg
from utils.model_analysis_utils import save_embeddings_all
from data.MEG import get_data
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
from trials.hyperparam_config import config
from main import parse_default_args

In [4]:
BAND_TO_OPT_C= { 
           'alpha':.54,
           'gamma':.66,
           'beta': .74,
            'theta':None
}

In [5]:
hyp_arch_dict={'model':'HGCN','optimizer':'RiemannianAdam','manifold':'PoincareBall'}
euc_arch_dict={'model':'GCN','optimizer':'Adam','manifold':'Euclidean'} 

In [6]:
arch_types={'full':{'use_weight':1,'use_virtual':1},
            'no_virt':{'use_weight':1,'use_virtual':0},
                'no_weight':{'use_weight':0,'use_virtual':1}}

input_types={'plv':{'use_plv':1,'use_identity':0,'num_feature':91},
             'id':{'use_plv':0,'use_identity':1,'num_feature':91},
             'id_plv':{'use_plv':1,'use_identity':1,'num_feature':181}}


curve_types={'setc':{**hyp_arch_dict,'c':'set'},
            'findc':{**hyp_arch_dict,'c':None},
            '1c':{**hyp_arch_dict,'c':1},
             'euc':{**euc_arch_dict,'c':0},
            }
curve_types

{'setc': {'model': 'HGCN',
  'optimizer': 'RiemannianAdam',
  'manifold': 'PoincareBall',
  'c': 'set'},
 'findc': {'model': 'HGCN',
  'optimizer': 'RiemannianAdam',
  'manifold': 'PoincareBall',
  'c': None},
 '1c': {'model': 'HGCN',
  'optimizer': 'RiemannianAdam',
  'manifold': 'PoincareBall',
  'c': 1},
 'euc': {'model': 'GCN', 'optimizer': 'Adam', 'manifold': 'Euclidean', 'c': 0}}

In [ ]:
# the total number of validation runs that all should have
NUM_VALIDATIONS=3
criteria={'CogTr':1}
criteria={}
set_args={'dataset':'meg',
          'task':'lp',
          'val_sub':0,
          'lr':.02,
          'use_batch':0,
          'stretch_sigmoid':0,
          'plv_norm_w_id':0,
          'plv_inp_raw':0,
          'unify_pos_neg_loss':0,
          'stretch_sigmoid':0,
          'use_weighted_bce':0,
          'criteria_dict':criteria}
criteria=criteria
output_dims=[3]
arch_types_to_use=['full']
input_types_to_use=['id_plv']
curve_types_to_use=['findc']
# raise Exception('OBVIOUSLY WE 'SHOULD ADD "CRITERIA INTO the folder name... dont want to mix those')
for d in output_dims:
    for i in input_types_to_use:
        inp_dict=input_types[i]
        for c_type in curve_types_to_use:
#             print(c,'C')
#             print(c_dict,'C DICT?')
            c_dict=curve_types[c_type]
#             print(c_dict,'')
            c_val=c_dict['c']
            print(c_val,'C VAL')
            if c_val=='set':
                c_set=BAND_TO_OPT_C['alpha']
                c_dict['c']=c_set
                
            set_args = copy.deepcopy(set_args)
            set_args['output_dim']=d
            set_args.update(c_dict)
            set_args.update(inp_dict)
            args = parse_default_args(set_args)
#             print(set_args['c'],set_args['use_identity'],set_args['use_plv'])
            print('compase')
            print('C: {}, ID: {}, PLV {}'.format(set_args['c'],set_args['use_identity'],set_args['use_plv']))
            print('C: {}, ID: {}, PLV {}'.format(args.c,args.use_identity,args.use_plv))
#             aka
            complete_study_one_arg(args,NUM_VALIDATIONS)
    
#             sksks
#             try:
#                 complete_study_one_arg(args,NUM_VALIDATIONS)
#             except:
#                 print('FUCKED THAT UP')
#             sksks
            
            

# # c=[1,None,.54]
# args = parse_default_args(set_args) ### still need to call this with args for dataset, possibly others
# complete_study_one_arg(args,NUM_VALIDATIONS)
# # print(args)
# # change_task(args,)

# # 
# # setattr(args,'criteria_dict',criteria)



INFO:root:Using: cpu


None C VAL
lp should match manual
lp 3
compase
C: None, ID: 1, PLV 1
C: None, ID: 1, PLV 1


HGCN_full_findc_plvid_dp model
HGCN_full_findc_plvid_dp model
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\april\all_pats\L3\HGCN_full_findc_plvid_dp\e100_p2fr5_lr0.02g0.9lf_10_strchinpvpct0.3_tpct0.2_95_bstrchloss95_lnmse_pn study dir
True exists for sure
['0', '1']
we are in here??
C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\april\all_pats\L3\HGCN_full_findc_plvid_dp\e100_p2fr5_lr0.02g0.9lf_10_strchinpvpct0.3_tpct0.2_95_bstrchloss95_lnmse_pn study directory!
meg ARG DATASET
in here 
graph DATA NAME
Names            ['Left Precentral gyrus']
Nicknames                       ['lPreCG']
Index                                    0
X                                 -0.03893
Y                                -0.006961
Z                                  0.04964
Source Count                            32
DMN Pct                                0.0
pD

(180, 90, 90) RIGHTOUT DATA
0.3309338126375074 80
0.32764641825358093 79
0.32456669569015506 78
0.316118533987748 75
0.34999029636383056 85
0.37674931507844195 90
0.4264068635304769 95
dict_keys(['mm_strech', 'ms_norm', 'ms_sigmoid', 'identity', 'add_noise', 'pca_transform']) keys
parsing scans as graphs...
0.0 ADD NOISE
0.9092297727387129 new standard
-0.1811374533330851 new mean
(90, 180) FEATS SHOULD BE HIGH
606
0.0 ADD NOISEessing: 0
0.8646270454984698 new standard
-0.2442406948795043 new mean
(90, 180) FEATS SHOULD BE HIGH
535
0.0 ADD NOISE
0.9785014624547117 new standard
0.031826183271803386 new mean
(90, 180) FEATS SHOULD BE HIGH
801
0.0 ADD NOISE
0.9706735082258283 new standard
0.023199741496544034 new mean
(90, 180) FEATS SHOULD BE HIGH
788
0.0 ADD NOISE
1.0093352598062335 new standard
0.12432307130148496 new mean
(90, 180) FEATS SHOULD BE HIGH
916
0.0 ADD NOISE
0.9379439837131297 new standard
-0.0810079259947177 new mean
(90, 180) FEATS SHOULD BE HIGH
670
0.0 ADD NOISE
1.0195

1.1043438464144628 new standard
0.16058998212552986 new mean
(90, 180) FEATS SHOULD BE HIGH
991
0.0 ADD NOISE
0.9819772183995533 new standard
-0.020708534192729385 new mean
(90, 180) FEATS SHOULD BE HIGH
799
0.0 ADD NOISE
0.9644553642357842 new standard
0.030098172039000455 new mean
(90, 180) FEATS SHOULD BE HIGH
810
0.0 ADD NOISE
1.0224227397036358 new standard
0.06973873236178516 new mean
(90, 180) FEATS SHOULD BE HIGH
859
0.0 ADD NOISE
1.011455050833746 new standard
0.1299679726242312 new mean
(90, 180) FEATS SHOULD BE HIGH
940
0.0 ADD NOISE
0.9941562756486371 new standard
-0.06910248610696036 new mean
(90, 180) FEATS SHOULD BE HIGH
760
0.0 ADD NOISE
1.0125286655231245 new standard
-0.06537930671924899 new mean
(90, 180) FEATS SHOULD BE HIGH
778
0.0 ADD NOISE
0.9412600403636379 new standard
-0.19387976930368225 new mean
(90, 180) FEATS SHOULD BE HIGH
647
0.0 ADD NOISEessing: 80
1.027328998586978 new standard
-0.061882993997553794 new mean
(90, 180) FEATS SHOULD BE HIGH
779
0.0 ADD N

1.0183939887715212 new standard
-0.05952872459682859 new mean
(90, 180) FEATS SHOULD BE HIGH
775
0.0 ADD NOISE
0.9607632415634426 new standard
0.08117599697748222 new mean
(90, 180) FEATS SHOULD BE HIGH
868
0.0 ADD NOISE
0.9937631997867223 new standard
0.09547327796011003 new mean
(90, 180) FEATS SHOULD BE HIGH
861
0.0 ADD NOISE
1.0756018739789066 new standard
0.06182738623797306 new mean
(90, 180) FEATS SHOULD BE HIGH
866
0.0 ADD NOISE
1.010497779943612 new standard
0.03258751411136219 new mean
(90, 180) FEATS SHOULD BE HIGH
865
0.0 ADD NOISE
1.0091441662714957 new standard
-0.15503073413291618 new mean
(90, 180) FEATS SHOULD BE HIGH
655
0.0 ADD NOISE
1.0248664600841668 new standard
-0.13203437656298173 new mean
(90, 180) FEATS SHOULD BE HIGH
688
0.0 ADD NOISE
1.0218546235650454 new standard
0.197495861844412 new mean
(90, 180) FEATS SHOULD BE HIGH
974
0.0 ADD NOISE
1.0607172527271291 new standard
0.20774441299973062 new mean
(90, 180) FEATS SHOULD BE HIGH
983
0.0 ADD NOISE
1.00801819

INFO:root:LPModel(
  (encoder): HGCN(
    (layers): Sequential(
      (0): HyperbolicGraphConvolution(
        (linear): HypLinear(
          in_features=181, out_features=6, c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (agg): HypAgg(
          c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (hyp_act): HypAct(
          c_in=Parameter containing:
          tensor([1.], requires_grad=True), c_out=Parameter containing:
          tensor([1.], requires_grad=True)
        )
      )
      (1): HyperbolicGraphConvolution(
        (linear): HypLinear(
          in_features=6, out_features=3, c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
        (agg): HypAgg(
          c=Parameter containing:
          tensor([1.], requires_grad=True)
        )
      )
    )
  )
  (dc): FermiDiracDecoder()
)
INFO:root:Total number of parameters: 1118.0


0.982706726974923 new standard
-0.14283895106767214 new mean
(90, 180) FEATS SHOULD BE HIGH
654
0.0 ADD NOISE
0.9638047913865534 new standard
-0.07703334506603277 new mean
(90, 180) FEATS SHOULD BE HIGH
706
0.0 ADD NOISE
0.9758408535515135 new standard
0.11149326817336414 new mean
(90, 180) FEATS SHOULD BE HIGH
854
0.0 ADD NOISE
1.0195171832106837 new standard
0.1317096815745789 new mean
(90, 180) FEATS SHOULD BE HIGH
916
test: 100 %      
180 unique ids
180 Final count
train SPLIT
True HAS TRAIN ONLY
0 USES TRAIN ONLY
[2, 3, 4, 5, 6, 7, 12, 13, 14, 15, 18, 19, 20, 21, 22, 23, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 43, 48, 49, 50, 51, 54, 55, 56, 57, 58, 59, 64, 65, 68, 69, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 96, 97, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 116, 117, 120, 121, 132, 133, 134, 135, 140, 141, 146, 147, 150, 151, 152, 153, 156, 157, 158, 159, 170, 171, 176, 177] SELF INDICES
['2', '3', '4', '5', '6', '7', '12', '13', '14', '15', '18', '19', '20', 

INFO:root:Epoch: 0001 lr: 0.02 train phase of epoch 0: precision 0.795169,roc 0.944137, loss 0.079026, acc 0, ECE 0 #edges 360450, #graphs 90 time: 161.4872s


90
2.0 1.0 FERMI (non-adjusting) epoch: 1 LR:  [0.02]
<generator object Module.parameters at 0x00000186D19B87C8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2133], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2133], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2133], requires_grad=True), c_out=Parameter containing:
    tensor([0.5332], requires_grad=True)
  )
)
tensor([-1.2181], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.5332], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.5332], requires_grad=True)
  )
)
tensor([-0.5414], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.5332], requires_grad=True)
model
<generator object Module.parameters at 0x00000

INFO:root:Epoch: 0002 lr: 0.02 train phase of epoch 1: precision 0.846976,roc 0.960616, loss 0.061302, acc 0, ECE 0 #edges 360450, #graphs 90 time: 155.4318s


90
2.0 1.0 FERMI (non-adjusting) epoch: 2 LR:  [0.02]
<generator object Module.parameters at 0x00000186D19B87C8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.1242], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.1242], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.1242], requires_grad=True), c_out=Parameter containing:
    tensor([0.4314], requires_grad=True)
  )
)
tensor([-1.1262], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4314], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4314], requires_grad=True)
  )
)
tensor([-0.4409], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4314], requires_grad=True)
model
<generator object Module.parameters at 0x00000

INFO:root:Epoch: 0003 lr: 0.02 train phase of epoch 2: precision 0.897979,roc 0.971821, loss 0.052154, acc 0, ECE 0 #edges 360450, #graphs 90 time: 155.4749s


90
2.0 1.0 FERMI (non-adjusting) epoch: 3 LR:  [0.02]
<generator object Module.parameters at 0x0000018681BDCF48> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2174], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2174], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2174], requires_grad=True), c_out=Parameter containing:
    tensor([0.3517], requires_grad=True)
  )
)
tensor([-1.2055], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.3517], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.3517], requires_grad=True)
  )
)
tensor([-0.3388], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.3517], requires_grad=True)
model
<generator object Module.parameters at 0x00000

INFO:root:Epoch: 0004 lr: 0.02 train phase of epoch 3: precision 0.911187,roc 0.975623, loss 0.048478, acc 0, ECE 0 #edges 360450, #graphs 90 time: 167.9945s


90
2.0 1.0 FERMI (non-adjusting) epoch: 4 LR:  [0.02]
<generator object Module.parameters at 0x00000186D19B87C8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.1702], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.1702], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.1702], requires_grad=True), c_out=Parameter containing:
    tensor([0.4165], requires_grad=True)
  )
)
tensor([-1.1701], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4165], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4165], requires_grad=True)
  )
)
tensor([-0.4111], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4165], requires_grad=True)
model
<generator object Module.parameters at 0x00000

INFO:root:Epoch: 0005 lr: 0.02 train phase of epoch 4: precision 0.917251,roc 0.977063, loss 0.046987, acc 0, ECE 0 #edges 360450, #graphs 90 time: 154.2661s


90
training epoch done in  time: 154.2661s
54
0.04578386607634715 0.9171822259213023 loss acc
54
0.04578386607634715 0.9171822259213023 loss acc


INFO:root:Dev Epoch: 0005 dev phase of epoch 4: precision 0.924127,roc 0.978234, loss 0.045784, acc 0, ECE 0 #edges 216270, #graphs 54
INFO:root:Saved model in C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\april\all_pats\L3\HGCN_full_findc_plvid_dp\e100_p2fr5_lr0.02g0.9lf_10_strchinpvpct0.3_tpct0.2_95_bstrchloss95_lnmse_pn\2


36
2.0 1.0 FERMI (non-adjusting) epoch: 5 LR:  [0.02]
<generator object Module.parameters at 0x00000186D2E56048> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.1432], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.1432], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.1432], requires_grad=True), c_out=Parameter containing:
    tensor([0.4081], requires_grad=True)
  )
)
tensor([-1.1396], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4081], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4081], requires_grad=True)
  )
)
tensor([-0.4054], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4081], requires_grad=True)
model
<generator object Module.parameters at 0x00000

INFO:root:Epoch: 0006 lr: 0.02 train phase of epoch 5: precision 0.921368,roc 0.977992, loss 0.046274, acc 0, ECE 0 #edges 360450, #graphs 90 time: 135.3051s


90
2.0 1.0 FERMI (non-adjusting) epoch: 6 LR:  [0.02]
<generator object Module.parameters at 0x0000018681BDCE48> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.1867], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.1867], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.1867], requires_grad=True), c_out=Parameter containing:
    tensor([0.4315], requires_grad=True)
  )
)
tensor([-1.1832], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4315], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4315], requires_grad=True)
  )
)
tensor([-0.4275], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4315], requires_grad=True)
model
<generator object Module.parameters at 0x00000

INFO:root:Epoch: 0007 lr: 0.02 train phase of epoch 6: precision 0.923715,roc 0.978674, loss 0.045509, acc 0, ECE 0 #edges 360450, #graphs 90 time: 145.2031s


90
2.0 1.0 FERMI (non-adjusting) epoch: 7 LR:  [0.02]
<generator object Module.parameters at 0x00000186D20F36C8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.1806], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.1806], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.1806], requires_grad=True), c_out=Parameter containing:
    tensor([0.4137], requires_grad=True)
  )
)
tensor([-1.1796], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4137], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4137], requires_grad=True)
  )
)
tensor([-0.4104], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4137], requires_grad=True)
model
<generator object Module.parameters at 0x00000

INFO:root:Epoch: 0008 lr: 0.02 train phase of epoch 7: precision 0.924693,roc 0.978746, loss 0.045785, acc 0, ECE 0 #edges 360450, #graphs 90 time: 111.2422s


90
2.0 1.0 FERMI (non-adjusting) epoch: 8 LR:  [0.02]
<generator object Module.parameters at 0x0000018681BDCF48> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2421], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2421], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2421], requires_grad=True), c_out=Parameter containing:
    tensor([0.5096], requires_grad=True)
  )
)
tensor([-1.2387], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.5096], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.5096], requires_grad=True)
  )
)
tensor([-0.5077], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.5096], requires_grad=True)
model
<generator object Module.parameters at 0x00000

INFO:root:Epoch: 0009 lr: 0.02 train phase of epoch 8: precision 0.926605,roc 0.979230, loss 0.044904, acc 0, ECE 0 #edges 360450, #graphs 90 time: 108.9976s


90
2.0 1.0 FERMI (non-adjusting) epoch: 9 LR:  [0.02]
<generator object Module.parameters at 0x0000018681BDCE48> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2160], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2160], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2160], requires_grad=True), c_out=Parameter containing:
    tensor([0.4511], requires_grad=True)
  )
)
tensor([-1.2145], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4511], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4511], requires_grad=True)
  )
)
tensor([-0.4505], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4511], requires_grad=True)
model
<generator object Module.parameters at 0x00000

INFO:root:Epoch: 0010 lr: 0.02 train phase of epoch 9: precision 0.928833,roc 0.980070, loss 0.044091, acc 0, ECE 0 #edges 360450, #graphs 90 time: 129.8592s


90
training epoch done in  time: 129.8592s
36
54
0.04378744440591153 0.9151985943496554 loss acc
54
0.04378744440591153 0.9151985943496554 loss acc


INFO:root:Dev Epoch: 0010 dev phase of epoch 9: precision 0.929843,roc 0.979788, loss 0.043787, acc 0, ECE 0 #edges 216270, #graphs 54
INFO:root:Saved model in C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\april\all_pats\L3\HGCN_full_findc_plvid_dp\e100_p2fr5_lr0.02g0.9lf_10_strchinpvpct0.3_tpct0.2_95_bstrchloss95_lnmse_pn\2


36
2.0 1.0 FERMI (non-adjusting) epoch: 10 LR:  [0.018000000000000002]
<generator object Module.parameters at 0x00000186D849F0C8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2123], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2123], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2123], requires_grad=True), c_out=Parameter containing:
    tensor([0.4064], requires_grad=True)
  )
)
tensor([-1.2141], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4064], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4064], requires_grad=True)
  )
)
tensor([-0.4066], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4064], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0011 lr: 0.018000000000000002 train phase of epoch 10: precision 0.926917,roc 0.979333, loss 0.045043, acc 0, ECE 0 #edges 360450, #graphs 90 time: 108.9791s


90
2.0 1.0 FERMI (non-adjusting) epoch: 11 LR:  [0.018000000000000002]
<generator object Module.parameters at 0x00000186D2BB50C8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2267], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2267], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2267], requires_grad=True), c_out=Parameter containing:
    tensor([0.4140], requires_grad=True)
  )
)
tensor([-1.2349], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4140], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4140], requires_grad=True)
  )
)
tensor([-0.4229], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4140], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0012 lr: 0.018000000000000002 train phase of epoch 11: precision 0.928829,roc 0.979999, loss 0.044039, acc 0, ECE 0 #edges 360450, #graphs 90 time: 109.1261s


90
2.0 1.0 FERMI (non-adjusting) epoch: 12 LR:  [0.018000000000000002]
<generator object Module.parameters at 0x00000186D2E56048> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2520], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2520], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2520], requires_grad=True), c_out=Parameter containing:
    tensor([0.4493], requires_grad=True)
  )
)
tensor([-1.2418], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4493], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4493], requires_grad=True)
  )
)
tensor([-0.4354], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4493], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0013 lr: 0.018000000000000002 train phase of epoch 12: precision 0.930096,roc 0.980240, loss 0.044133, acc 0, ECE 0 #edges 360450, #graphs 90 time: 381.3433s


90
2.0 1.0 FERMI (non-adjusting) epoch: 13 LR:  [0.018000000000000002]
<generator object Module.parameters at 0x00000186D2BB5048> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2410], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2410], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2410], requires_grad=True), c_out=Parameter containing:
    tensor([0.4328], requires_grad=True)
  )
)
tensor([-1.2357], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4328], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4328], requires_grad=True)
  )
)
tensor([-0.4258], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4328], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0014 lr: 0.018000000000000002 train phase of epoch 13: precision 0.929946,roc 0.980280, loss 0.043696, acc 0, ECE 0 #edges 360450, #graphs 90 time: 154.8602s


90
2.0 1.0 FERMI (non-adjusting) epoch: 14 LR:  [0.018000000000000002]
<generator object Module.parameters at 0x00000186D2BB5048> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2225], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2225], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2225], requires_grad=True), c_out=Parameter containing:
    tensor([0.4075], requires_grad=True)
  )
)
tensor([-1.2219], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4075], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4075], requires_grad=True)
  )
)
tensor([-0.4063], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4075], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0015 lr: 0.018000000000000002 train phase of epoch 14: precision 0.929684,roc 0.980190, loss 0.043832, acc 0, ECE 0 #edges 360450, #graphs 90 time: 124.3045s


90
training epoch done in  time: 124.3045s
36
54
0.043195748473052124 0.9137143385582838 loss acc
54
0.043195748473052124 0.9137143385582838 loss acc


INFO:root:Dev Epoch: 0015 dev phase of epoch 14: precision 0.932354,roc 0.980439, loss 0.043196, acc 0, ECE 0 #edges 216270, #graphs 54
INFO:root:Saved model in C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\april\all_pats\L3\HGCN_full_findc_plvid_dp\e100_p2fr5_lr0.02g0.9lf_10_strchinpvpct0.3_tpct0.2_95_bstrchloss95_lnmse_pn\2


36
2.0 1.0 FERMI (non-adjusting) epoch: 15 LR:  [0.018000000000000002]
<generator object Module.parameters at 0x00000186FF06C0C8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2692], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2692], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2692], requires_grad=True), c_out=Parameter containing:
    tensor([0.4356], requires_grad=True)
  )
)
tensor([-1.2697], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4356], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4356], requires_grad=True)
  )
)
tensor([-0.4368], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4356], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0016 lr: 0.018000000000000002 train phase of epoch 15: precision 0.931584,roc 0.980745, loss 0.043453, acc 0, ECE 0 #edges 360450, #graphs 90 time: 115.6327s


90
2.0 1.0 FERMI (non-adjusting) epoch: 16 LR:  [0.018000000000000002]
<generator object Module.parameters at 0x00000186FF06C048> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2722], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2722], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2722], requires_grad=True), c_out=Parameter containing:
    tensor([0.4586], requires_grad=True)
  )
)
tensor([-1.2753], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4586], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4586], requires_grad=True)
  )
)
tensor([-0.4611], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4586], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0017 lr: 0.018000000000000002 train phase of epoch 16: precision 0.931098,roc 0.980637, loss 0.043412, acc 0, ECE 0 #edges 360450, #graphs 90 time: 129.8666s


90
2.0 1.0 FERMI (non-adjusting) epoch: 17 LR:  [0.018000000000000002]
<generator object Module.parameters at 0x00000186FF06C048> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2657], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2657], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2657], requires_grad=True), c_out=Parameter containing:
    tensor([0.4393], requires_grad=True)
  )
)
tensor([-1.2612], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4393], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4393], requires_grad=True)
  )
)
tensor([-0.4348], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4393], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0018 lr: 0.018000000000000002 train phase of epoch 17: precision 0.932353,roc 0.980937, loss 0.043147, acc 0, ECE 0 #edges 360450, #graphs 90 time: 124.1830s


90
2.0 1.0 FERMI (non-adjusting) epoch: 18 LR:  [0.018000000000000002]
<generator object Module.parameters at 0x00000186D20F36C8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2447], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2447], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2447], requires_grad=True), c_out=Parameter containing:
    tensor([0.4349], requires_grad=True)
  )
)
tensor([-1.2473], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4349], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4349], requires_grad=True)
  )
)
tensor([-0.4386], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4349], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0019 lr: 0.018000000000000002 train phase of epoch 18: precision 0.931384,roc 0.980741, loss 0.043266, acc 0, ECE 0 #edges 360450, #graphs 90 time: 116.8600s


90
2.0 1.0 FERMI (non-adjusting) epoch: 19 LR:  [0.018000000000000002]
<generator object Module.parameters at 0x0000018681BDCE48> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2675], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2675], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2675], requires_grad=True), c_out=Parameter containing:
    tensor([0.4596], requires_grad=True)
  )
)
tensor([-1.2682], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4596], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4596], requires_grad=True)
  )
)
tensor([-0.4604], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4596], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0020 lr: 0.018000000000000002 train phase of epoch 19: precision 0.931936,roc 0.980772, loss 0.043179, acc 0, ECE 0 #edges 360450, #graphs 90 time: 115.6240s


90
training epoch done in  time: 115.6240s
36
54
0.043570694252898334 0.9148518056133539 loss acc
54
0.043570694252898334 0.9148518056133539 loss acc


INFO:root:Dev Epoch: 0020 dev phase of epoch 19: precision 0.930786,roc 0.979927, loss 0.043571, acc 0, ECE 0 #edges 216270, #graphs 54


36
2.0 1.0 FERMI (non-adjusting) epoch: 20 LR:  [0.016200000000000003]
<generator object Module.parameters at 0x0000018681BDCE48> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2719], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2719], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2719], requires_grad=True), c_out=Parameter containing:
    tensor([0.4206], requires_grad=True)
  )
)
tensor([-1.2766], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4206], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4206], requires_grad=True)
  )
)
tensor([-0.4251], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4206], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0021 lr: 0.016200000000000003 train phase of epoch 20: precision 0.931365,roc 0.980595, loss 0.043407, acc 0, ECE 0 #edges 360450, #graphs 90 time: 155.9813s


90
2.0 1.0 FERMI (non-adjusting) epoch: 21 LR:  [0.016200000000000003]
<generator object Module.parameters at 0x0000018681BDCEC8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2811], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2811], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2811], requires_grad=True), c_out=Parameter containing:
    tensor([0.4419], requires_grad=True)
  )
)
tensor([-1.2831], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4419], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4419], requires_grad=True)
  )
)
tensor([-0.4445], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4419], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0022 lr: 0.016200000000000003 train phase of epoch 21: precision 0.932415,roc 0.980989, loss 0.043000, acc 0, ECE 0 #edges 360450, #graphs 90 time: 120.9787s


90
2.0 1.0 FERMI (non-adjusting) epoch: 22 LR:  [0.016200000000000003]
<generator object Module.parameters at 0x0000018681BDCF48> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2338], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2338], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2338], requires_grad=True), c_out=Parameter containing:
    tensor([0.4033], requires_grad=True)
  )
)
tensor([-1.2349], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4033], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4033], requires_grad=True)
  )
)
tensor([-0.4044], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4033], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0023 lr: 0.016200000000000003 train phase of epoch 22: precision 0.933156,roc 0.981200, loss 0.042998, acc 0, ECE 0 #edges 360450, #graphs 90 time: 118.1646s


90
2.0 1.0 FERMI (non-adjusting) epoch: 23 LR:  [0.016200000000000003]
<generator object Module.parameters at 0x00000186DE718048> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2475], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2475], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2475], requires_grad=True), c_out=Parameter containing:
    tensor([0.4112], requires_grad=True)
  )
)
tensor([-1.2417], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4112], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4112], requires_grad=True)
  )
)
tensor([-0.4040], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4112], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0024 lr: 0.016200000000000003 train phase of epoch 23: precision 0.932366,roc 0.980954, loss 0.043017, acc 0, ECE 0 #edges 360450, #graphs 90 time: 147.1152s


90
2.0 1.0 FERMI (non-adjusting) epoch: 24 LR:  [0.016200000000000003]
<generator object Module.parameters at 0x00000186E742A048> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2794], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2794], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2794], requires_grad=True), c_out=Parameter containing:
    tensor([0.4451], requires_grad=True)
  )
)
tensor([-1.2757], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4451], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4451], requires_grad=True)
  )
)
tensor([-0.4405], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4451], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0025 lr: 0.016200000000000003 train phase of epoch 24: precision 0.932902,roc 0.981134, loss 0.042893, acc 0, ECE 0 #edges 360450, #graphs 90 time: 120.8935s


90
training epoch done in  time: 120.8935s
36
54
0.043192791677868006 0.9195172700790679 loss acc
54
0.043192791677868006 0.9195172700790679 loss acc


INFO:root:Dev Epoch: 0025 dev phase of epoch 24: precision 0.932921,roc 0.980497, loss 0.043193, acc 0, ECE 0 #edges 216270, #graphs 54
INFO:root:Saved model in C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\april\all_pats\L3\HGCN_full_findc_plvid_dp\e100_p2fr5_lr0.02g0.9lf_10_strchinpvpct0.3_tpct0.2_95_bstrchloss95_lnmse_pn\2


36
2.0 1.0 FERMI (non-adjusting) epoch: 25 LR:  [0.016200000000000003]
<generator object Module.parameters at 0x000001868A7E5048> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2641], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2641], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2641], requires_grad=True), c_out=Parameter containing:
    tensor([0.3924], requires_grad=True)
  )
)
tensor([-1.2642], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.3924], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.3924], requires_grad=True)
  )
)
tensor([-0.3936], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.3924], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0026 lr: 0.016200000000000003 train phase of epoch 25: precision 0.933752,roc 0.981320, loss 0.042575, acc 0, ECE 0 #edges 360450, #graphs 90 time: 128.1215s


90
2.0 1.0 FERMI (non-adjusting) epoch: 26 LR:  [0.016200000000000003]
<generator object Module.parameters at 0x00000186E742A048> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2847], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2847], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2847], requires_grad=True), c_out=Parameter containing:
    tensor([0.4363], requires_grad=True)
  )
)
tensor([-1.2804], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4363], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4363], requires_grad=True)
  )
)
tensor([-0.4320], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4363], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0027 lr: 0.016200000000000003 train phase of epoch 26: precision 0.934026,roc 0.981416, loss 0.042507, acc 0, ECE 0 #edges 360450, #graphs 90 time: 139.0809s


90
2.0 1.0 FERMI (non-adjusting) epoch: 27 LR:  [0.016200000000000003]
<generator object Module.parameters at 0x00000186E742A048> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2807], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2807], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2807], requires_grad=True), c_out=Parameter containing:
    tensor([0.4244], requires_grad=True)
  )
)
tensor([-1.2815], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4244], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4244], requires_grad=True)
  )
)
tensor([-0.4256], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4244], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0028 lr: 0.016200000000000003 train phase of epoch 27: precision 0.934314,roc 0.981524, loss 0.042410, acc 0, ECE 0 #edges 360450, #graphs 90 time: 151.5091s


90
2.0 1.0 FERMI (non-adjusting) epoch: 28 LR:  [0.016200000000000003]
<generator object Module.parameters at 0x00000186D882E2C8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2709], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2709], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2709], requires_grad=True), c_out=Parameter containing:
    tensor([0.4198], requires_grad=True)
  )
)
tensor([-1.2671], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4198], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4198], requires_grad=True)
  )
)
tensor([-0.4153], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4198], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0029 lr: 0.016200000000000003 train phase of epoch 28: precision 0.933433,roc 0.981235, loss 0.042572, acc 0, ECE 0 #edges 360450, #graphs 90 time: 261.0454s


90
2.0 1.0 FERMI (non-adjusting) epoch: 29 LR:  [0.016200000000000003]
<generator object Module.parameters at 0x00000186E742A0C8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.3126], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.3126], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.3126], requires_grad=True), c_out=Parameter containing:
    tensor([0.4279], requires_grad=True)
  )
)
tensor([-1.3127], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4279], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4279], requires_grad=True)
  )
)
tensor([-0.4266], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4279], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0030 lr: 0.016200000000000003 train phase of epoch 29: precision 0.934518,roc 0.981596, loss 0.042350, acc 0, ECE 0 #edges 360450, #graphs 90 time: 285.8676s


90
training epoch done in  time: 285.8843s
36
54
0.04301484765899483 0.9089933878947613 loss acc
54
0.04301484765899483 0.9089933878947613 loss acc


INFO:root:Dev Epoch: 0030 dev phase of epoch 29: precision 0.934559,roc 0.980908, loss 0.043015, acc 0, ECE 0 #edges 216270, #graphs 54
INFO:root:Saved model in C:\Users\coleb\OneDrive\Desktop\Fall 2021\Neuro\hyperBrain\study\meg\lp\april\all_pats\L3\HGCN_full_findc_plvid_dp\e100_p2fr5_lr0.02g0.9lf_10_strchinpvpct0.3_tpct0.2_95_bstrchloss95_lnmse_pn\2


36
2.0 1.0 FERMI (non-adjusting) epoch: 30 LR:  [0.014580000000000003]
<generator object Module.parameters at 0x00000186E742A048> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.3186], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.3186], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.3186], requires_grad=True), c_out=Parameter containing:
    tensor([0.4421], requires_grad=True)
  )
)
tensor([-1.3162], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4421], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4421], requires_grad=True)
  )
)
tensor([-0.4387], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4421], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0031 lr: 0.014580000000000003 train phase of epoch 30: precision 0.934663,roc 0.981599, loss 0.042132, acc 0, ECE 0 #edges 360450, #graphs 90 time: 145.8172s


90
2.0 1.0 FERMI (non-adjusting) epoch: 31 LR:  [0.014580000000000003]
<generator object Module.parameters at 0x00000186D882E348> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2842], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2842], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2842], requires_grad=True), c_out=Parameter containing:
    tensor([0.4371], requires_grad=True)
  )
)
tensor([-1.2826], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4371], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4371], requires_grad=True)
  )
)
tensor([-0.4340], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4371], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0032 lr: 0.014580000000000003 train phase of epoch 31: precision 0.934073,roc 0.981398, loss 0.042412, acc 0, ECE 0 #edges 360450, #graphs 90 time: 125.3330s


90
2.0 1.0 FERMI (non-adjusting) epoch: 32 LR:  [0.014580000000000003]
<generator object Module.parameters at 0x00000186D882E3C8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2935], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2935], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2935], requires_grad=True), c_out=Parameter containing:
    tensor([0.4117], requires_grad=True)
  )
)
tensor([-1.2940], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4117], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4117], requires_grad=True)
  )
)
tensor([-0.4129], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4117], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0033 lr: 0.014580000000000003 train phase of epoch 32: precision 0.934433,roc 0.981554, loss 0.042207, acc 0, ECE 0 #edges 360450, #graphs 90 time: 122.1547s


90
2.0 1.0 FERMI (non-adjusting) epoch: 33 LR:  [0.014580000000000003]
<generator object Module.parameters at 0x00000186D882E3C8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2841], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2841], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2841], requires_grad=True), c_out=Parameter containing:
    tensor([0.4273], requires_grad=True)
  )
)
tensor([-1.2857], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4273], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4273], requires_grad=True)
  )
)
tensor([-0.4280], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4273], requires_grad=True)
model
<generator object Module.para

INFO:root:Epoch: 0034 lr: 0.014580000000000003 train phase of epoch 33: precision 0.935614,roc 0.981860, loss 0.042055, acc 0, ECE 0 #edges 360450, #graphs 90 time: 124.9163s


90
2.0 1.0 FERMI (non-adjusting) epoch: 34 LR:  [0.014580000000000003]
<generator object Module.parameters at 0x00000186D882E3C8> MODEL PARAMS
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=181, out_features=6, c=Parameter containing:
    tensor([1.2825], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([1.2825], requires_grad=True)
  )
  (hyp_act): HypAct(
    c_in=Parameter containing:
    tensor([1.2825], requires_grad=True), c_out=Parameter containing:
    tensor([0.4189], requires_grad=True)
  )
)
tensor([-1.2778], grad_fn=<NegBackward0>) agg man
HyperbolicGraphConvolution(
  (linear): HypLinear(
    in_features=6, out_features=3, c=Parameter containing:
    tensor([0.4189], requires_grad=True)
  )
  (agg): HypAgg(
    c=Parameter containing:
    tensor([0.4189], requires_grad=True)
  )
)
tensor([-0.4126], grad_fn=<NegBackward0>) agg man
Parameter containing:
tensor([0.4189], requires_grad=True)
model
<generator object Module.para

In [ ]:
from models.base_models import NCModel, LPModel


In [ ]:
model = LPModel({})

In [ ]:
# the total number of validation runs that all should have
NUM_VALIDATIONS=3
criteria={'CogTr':1}
criteria={}
set_args={'dataset':'meg',
          'task':'lp',
          'val_sub':0,
          'lr':.021,
          'stretch_sigmoid':0,
          'plv_norm_w_id':0,
          'plv_inp_raw':0,
          'unify_pos_neg_loss':0,
          'stretch_sigmoid':0,
          'use_weighted_bce':0,
          'criteria_dict':criteria}
criteria=criteria
output_dims=[3]
arch_types_to_use=['full']
input_types_to_use=['id']
curve_types_to_use=['findc']
# raise Exception('OBVIOUSLY WE 'SHOULD ADD "CRITERIA INTO the folder name... dont want to mix those')
for d in output_dims:
    for i in input_types_to_use:
        inp_dict=input_types[i]
        for c_type in curve_types_to_use:
#             print(c,'C')
#             print(c_dict,'C DICT?')
            c_dict=curve_types[c_type]
#             print(c_dict,'')
            c_val=c_dict['c']
            print(c_val,'C VAL')
            if c_val=='set':
                c_set=BAND_TO_OPT_C['alpha']
                c_dict['c']=c_set
                
            set_args = copy.deepcopy(set_args)
            set_args['output_dim']=d
            set_args.update(c_dict)
            set_args.update(inp_dict)
            args = parse_default_args(set_args)
#             print(set_args['c'],set_args['use_identity'],set_args['use_plv'])
            print('compase')
            print('C: {}, ID: {}, PLV {}'.format(set_args['c'],set_args['use_identity'],set_args['use_plv']))
            print('C: {}, ID: {}, PLV {}'.format(args.c,args.use_identity,args.use_plv))
#             aka
            complete_study_one_arg(args,NUM_VALIDATIONS)
    
#             sksks
#             try:
#                 complete_study_one_arg(args,NUM_VALIDATIONS)
#             except:
#                 print('FUCKED THAT UP')
#             sksks
            
            

# # c=[1,None,.54]
# args = parse_default_args(set_args) ### still need to call this with args for dataset, possibly others
# complete_study_one_arg(args,NUM_VALIDATIONS)
# # print(args)
# # change_task(args,)

# # 
# # setattr(args,'criteria_dict',criteria)